### PR TITLE
LIIKUNTA-651 | fix(test): fix packages/components tests, remove unnecessary type casts

### PR DESCRIPTION
**Pull request by karisal-anders**
### fix(test): fix packages/components tests, remove unnecessary type casts

```
yarn
cd packages/components
yarn test
```
->
```
Test Suites: 1 skipped, 64 passed, 64 of 65 total
Tests:       24 skipped, 226 passed, 250 total
Snapshots:   28 passed, 28 total
Time:        34.789 s, estimated 36 s
Ran all test suites.
```

refs LIIKUNTA-651

### Related

[LIIKUNTA-651](https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-651)

## Additional notes

[LIIKUNTA-651]: https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-651?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by terovirtanen** [comment]
**Events-Helsinki branch is deployed to platta: https://tapahtumat-pr695.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Hobbies-Helsinki branch is deployed to platta: https://harrastukset-pr695.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Sports-Helsinki branch is deployed to platta: https://liikunta-pr695.dev.hel.ninja** :rocket::rocket::rocket:

**Review by melniiv — APPROVED** [review]

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://liikunta-pr695.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://harrastukset-pr695.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://tapahtumat-pr695.dev.hel.ninja :laughing::tada::tada::tada:

**Pull request merged**
