### PR TITLE
fix: large card mobile view new hcrc version

### PR DESCRIPTION
**Pull request by melniiv**
## Description
Large card on mobile should look like normal card in vertical fixed view
Screenshot 2022-12-10 at 17 49 15

### Closes

**[DEV-XXX](https://helsinkisolutionoffice.atlassian.net/browse/DEV-XXX):**

### CODE REVIEW

**Comment by terovirtanen** [comment]
**Hobbies-Helsinki branch is deployed to platta: https://harrastukset-104-hcrc-79-large-card.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Events-Helsinki branch is deployed to platta: https://tapahtumat-104-hcrc-79-large-card.dev.hel.ninja** :rocket::rocket::rocket:

**Review by nikomakela — APPROVED** [review]

**Comment by nikomakela** [comment]
NOTE: `yarn check:install` fails. It should be addressed

**Comment by terovirtanen** [comment]
**Sports-Helsinki branch is deployed to platta: https://liikunta-104-hcrc-79-large-card.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Hobbies-Helsinki branch is deployed to platta: https://harrastukset-104-hcrc-79-large-card.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Events-Helsinki branch is deployed to platta: https://tapahtumat-104-hcrc-79-large-card.dev.hel.ninja** :rocket::rocket::rocket:

**Pull request merged**
