### PR TITLE
Liikunta-389: improve performance of jest tests

### PR DESCRIPTION
**Pull request by nenonja**
## Description
- Trying out  @swc/jest. Looks like it's about 30-50% faster than ts-jest.

**With  `ts-jest`:**

**Single test locally run:**
```
EventsPageContainer.test
 PASS   sports-helsinki:unit  src/domain/event/__tests__/EventPageContainer.test.tsx (28.12 s)
  ✓ should render info and load other events + similar events (4839 ms)
  ✓ should show error info when event is closed (154 ms)
  ✓ should show error info when event doesn't exist (112 ms)
  ✓ should link to events search when clicking tags (1633 ms)
Time:        28.651 s
```

**with `@swc/jest`:**
```
 PASS   sports-helsinki:unit  src/domain/event/__tests__/EventPageContainer.test.tsx (14.286 s)
  ✓ should render info and load other events + similar events (4565 ms)
  ✓ should show error info when event is closed (141 ms)
  ✓ should show error info when event doesn't exist (116 ms)
  ✓ should link to events search when clicking tags (1864 ms)
Time:        15.065 s
```

**Sports pipeline:**

**With  `ts-jest`:** 
https://dev.azure.com/City-of-Helsinki/liikunta/_build/results?buildId=66598&view=logs&j=8267e077-3a31-5bba-93c5-4b3e55896ad0&t=f69267ae-8804-5590-a878-6662f5a5eb23
```
Test Suites: 1 skipped, 27 passed, 27 of 28 total
Tests:       6 skipped, 1 todo, 104 passed, 111 total
Snapshots:   8 passed, 8 total
Time:        169.615 s
Ran all test suites.
```

**with `@swc/jest`:**
https://dev.azure.com/City-of-Helsinki/liikunta/_build/results?buildId=66996&view=logs&j=8267e077-3a31-5bba-93c5-4b3e55896ad0&t=f69267ae-8804-5590-a878-6662f5a5eb23
```
Test Suites: 1 skipped, 27 passed, 27 of 28 total
Tests:       6 skipped, 1 todo, 104 passed, 111 total
Snapshots:   8 passed, 8 total
Time:        122.831 s
Ran all test suites.
```

**Events pipeline:**

**With  `ts-jest`:** 
https://dev.azure.com/City-of-Helsinki/tapahtumat/_build/results?buildId=66764&view=logs&j=8267e077-3a31-5bba-93c5-4b3e55896ad0&t=f69267ae-8804-5590-a878-6662f5a5eb23
```
Test Suites: 27 passed, 27 total
Tests:       7 skipped, 7 todo, 142 passed, 156 total
Snapshots:   5 passed, 5 total
Time:        223.787 s
Ran all test suites.
Finishing: Unit tests
```

**with `@swc/jest`:**
https://dev.azure.com/City-of-Helsinki/tapahtumat/_build/results?buildId=66995&view=logs&j=8267e077-3a31-5bba-93c5-4b3e55896ad0&t=f69267ae-8804-5590-a878-6662f5a5eb23
```
Test Suites: 27 passed, 27 total
Tests:       11 skipped, 7 todo, 138 passed, 156 total
Snapshots:   5 passed, 5 total
Time:        179.136 s
Ran all test suites.
```

**Events pipeline:**

**With  `ts-jest`:** 
https://dev.azure.com/City-of-Helsinki/harrastukset/_build/results?buildId=66801&view=logs&j=8267e077-3a31-5bba-93c5-4b3e55896ad0&t=f69267ae-8804-5590-a878-6662f5a5eb23
```
Test Suites: 25 passed, 25 total
Tests:       7 skipped, 6 todo, 107 passed, 120 total
Snapshots:   4 passed, 4 total
Time:        216.819 s
Ran all test suites.
```

**with `@swc/jest`:**
https://dev.azure.com/City-of-Helsinki/harrastukset/_build/results?buildId=66994&view=logs&j=8267e077-3a31-5bba-93c5-4b3e55896ad0&t=f69267ae-8804-5590-a878-6662f5a5eb23
```
Test Suites: 25 passed, 25 total
Tests:       7 skipped, 6 todo, 107 passed, 120 total
Snapshots:   4 passed, 4 total
Time:        176.476 s
Ran all test suites.
```

-  WIP
### Closes

**[DEV-XXX](https://helsinkisolutionoffice.atlassian.net/browse/DEV-XXX):**

### CODE REVIEW

**Comment by terovirtanen** [comment]
**Events-Helsinki branch is deployed to platta: https://tapahtumat-pr197.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Sports-Helsinki branch is deployed to platta: https://liikunta-pr197.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**$(upper(replace(parameters.proxy,'-', ' '))) is deployed to platta: https://events-graphql-proxy-pr197.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**$(upper(replace(parameters.proxy,'-', ' '))) is deployed to platta: https://venue-graphql-proxy-pr197.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://liikunta-pr197.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://tapahtumat-pr197.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**Hobbies-Helsinki branch is deployed to platta: https://harrastukset-pr197.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Hobbies-Helsinki branch is deployed to platta: https://harrastukset-pr197.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Sports-Helsinki branch is deployed to platta: https://liikunta-pr197.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://harrastukset-pr197.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**Hobbies-Helsinki branch is deployed to platta: https://harrastukset-pr197.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Hobbies-Helsinki branch is deployed to platta: https://harrastukset-pr197.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Sports-Helsinki branch is deployed to platta: https://liikunta-pr197.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://harrastukset-pr197.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://liikunta-pr197.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**$(upper(replace(parameters.proxy,'-', ' '))) is deployed to platta: https://events-graphql-proxy-pr197.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Hobbies-Helsinki branch is deployed to platta: https://harrastukset-pr197.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Sports-Helsinki branch is deployed to platta: https://liikunta-pr197.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://harrastukset-pr197.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://liikunta-pr197.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**$(upper(replace(parameters.proxy,'-', ' '))) is deployed to platta: https://events-graphql-proxy-pr197.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**$(upper(replace(parameters.proxy,'-', ' '))) is deployed to platta: https://venue-graphql-proxy-pr197.dev.hel.ninja** :rocket::rocket::rocket:

**Review by nikomakela — APPROVED** [review]
Nice! I tested and I have to admit that it works a lot better. Much improved. SWC benchmarks: https://swc.rs/docs/benchmarks

**Pull request merged**
