### PR TITLE
feat: article search with query params

### PR DESCRIPTION
**Pull request by melniiv**
## Description
- In all 3 apps article search now works with search query params (even though hcrc supports both state and url params search)
- Article page tags are redirecting to the article search with tag parameter (if app configured to use search query params, otherwise tags are not clickable)
- Fixed bug with clear search parameter

### Closes

**[DEV-XXX](https://helsinkisolutionoffice.atlassian.net/browse/DEV-XXX):**

### CODE REVIEW

**Comment by karisal-anders** [comment]
It would be good to update `hds-core`, `hds-react` and `hds-design-tokens` packages to `^3.3.0` like was done in HCRC side already in  https://github.com/City-of-Helsinki/react-helsinki-headless-cms/pull/154

**Review by karisal-anders — APPROVED** [review]
It would be good to refactor the triplicated code or move identical functions to under packages/components

**Comment by terovirtanen** [comment]
**Sports-Helsinki branch is deployed to platta: https://liikunta-pr605.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Hobbies-Helsinki branch is deployed to platta: https://harrastukset-pr605.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**EVENTS GRAPHQL PROXY is deployed to platta: https://events-graphql-proxy-pr605.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://liikunta-pr605.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**Events-Helsinki branch is deployed to platta: https://tapahtumat-pr605.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**VENUE GRAPHQL PROXY is deployed to platta: https://venue-graphql-proxy-pr605.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://harrastukset-pr605.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://tapahtumat-pr605.dev.hel.ninja :laughing::tada::tada::tada:

**Pull request merged**
