### PR TITLE
LIIKUNTA-431 | fix(sports): fix venue search order by

### PR DESCRIPTION
**Pull request by karisal-anders**
### fix(sports): fix venue search order by 

remove (as unnecessary):
 - useSearchPage.tsx:
   - setFilters call
 - useUnifiedSearch.ts:
   - filterList + related tests
   - filterListBehaviour
   - getIsArrayKind
   - getQueryWithout + related tests
   - getSafeArrayValue
   - getSearchParamsFromFilters + related tests
   - if (pathname) clause in setFilters
   - modifyFilters + related tests
   - queryPersister
   - SpreadFilter
 - unifiedSearch/types.ts:
   - ModifyFilters
 - UnifiedSearch.test.js:
   - MockQueryPersister
   - queryPersister parameter to UnifiedSearch

add:
 - useSetOrderByAndDirQueryParams hook
 - null/undefined handling to UnifiedSearch's query function for added
   robustness

rename:
 - useHandleUnifiedSearchOrderChange.ts:
   - by -> orderBy
   - dir -> orderDir

use:
 - useSetOrderByAndDirQueryParams hook in
   useHandleUnifiedSearchOrderChange to set the order by and order dir
   for the venue search

change:
 - UnifiedSearch.test.js:
   - test case "should not be calling router without pathname" ->
     "should be calling router without pathname" in name and
     functionality

refs LIIKUNTA-431 (fixing venue search order by)
refs LIIKUNTA-418 (load more in venue search should still work)
 
### chore: remove queryPersister and its tests as unused 

refs LIIKUNTA-431 (removed the use of queryPersister)
 
### fix(sports): use q query parameter only, fix query parameter combining 

replace completely:
 - use of `text` query parameter with the use of `q` query parameter
   for free text search in venue/events/hobbies/combined search

fix:
 - dropping `orderBy`, `orderDir` and `sort` query parameters when
   changing sports categories filterings, removing filters from
   FilterSummary, changing free text search value etc

refs LIIKUNTA-431

### Closes

**[LIIKUNTA-431](https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-431)**

### Related

**[LIIKUNTA-418](https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-418)**

## Additional notes

[LIIKUNTA-431]: https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-431?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by terovirtanen** [comment]
**Events-Helsinki branch is deployed to platta: https://tapahtumat-pr279.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://harrastukset-pr279.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**Sports-Helsinki branch is deployed to platta: https://liikunta-pr279.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**EVENTS GRAPHQL PROXY is deployed to platta: https://events-graphql-proxy-pr279.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://tapahtumat-pr279.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://liikunta-pr279.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**VENUE GRAPHQL PROXY is deployed to platta: https://venue-graphql-proxy-pr279.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Hobbies-Helsinki branch is deployed to platta: https://harrastukset-pr279.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://harrastukset-pr279.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**Events-Helsinki branch is deployed to platta: https://tapahtumat-pr279.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**VENUE GRAPHQL PROXY is deployed to platta: https://venue-graphql-proxy-pr279.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Sports-Helsinki branch is deployed to platta: https://liikunta-pr279.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://liikunta-pr279.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**Hobbies-Helsinki branch is deployed to platta: https://harrastukset-pr279.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Events-Helsinki branch is deployed to platta: https://tapahtumat-pr279.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://harrastukset-pr279.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://tapahtumat-pr279.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**EVENTS GRAPHQL PROXY is deployed to platta: https://events-graphql-proxy-pr279.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**VENUE GRAPHQL PROXY is deployed to platta: https://venue-graphql-proxy-pr279.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Sports-Helsinki branch is deployed to platta: https://liikunta-pr279.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by karisal-anders** [comment]
TODO:
 - [ ] Fix simultaneous use of order by and sportsCategories filtering

**Comment by terovirtanen** [comment]
**Hobbies-Helsinki branch is deployed to platta: https://harrastukset-pr279.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Events-Helsinki branch is deployed to platta: https://tapahtumat-pr279.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://tapahtumat-pr279.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**EVENTS GRAPHQL PROXY is deployed to platta: https://events-graphql-proxy-pr279.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://liikunta-pr279.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**VENUE GRAPHQL PROXY is deployed to platta: https://venue-graphql-proxy-pr279.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Hobbies-Helsinki branch is deployed to platta: https://harrastukset-pr279.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://harrastukset-pr279.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**Events-Helsinki branch is deployed to platta: https://tapahtumat-pr279.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Sports-Helsinki branch is deployed to platta: https://liikunta-pr279.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**VENUE GRAPHQL PROXY is deployed to platta: https://venue-graphql-proxy-pr279.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://liikunta-pr279.dev.hel.ninja :laughing::tada::tada::tada:

**Pull request merged**
