### PR TITLE
LIIKUNTA-495 | Update sports categories

### PR DESCRIPTION
**Pull request by karisal-anders**
### feat(sports): add playgrounds sports category (summer & winter) 

refs LIIKUNTA-495
 
### feat(sports): add tennis sports category (summer only) 

refs LIIKUNTA-495
 
### feat(sports): add skateboarding sports category (summer only) 

refs LIIKUNTA-495
 
### fix(sports): remove unneeded neighbourhood sports sites sports category 

refs LIIKUNTA-495
 
### fix(sports): set guided exercise sports category's season to winter only 

refs LIIKUNTA-495
 
### feat(sports): add outdoor gyms sports category (summer only) 

yso:p3413 i.e. https://api.hel.fi/linkedevents/v1/keyword/yso:p3413/
is not an exact keyword for outdoor gyms but as the other option of
setting the keyword list to an empty one (this was tried already)
resulted in more problems than this so an inexact keyword was chosen
which at the moment (2023-05-02) returned 6 events in LinkedEvents
production:
 - https://api.hel.fi/linkedevents/v1/event/?keyword=yso:p3413

The returned events were relatively close to outdoor gyms even if not
exactly that.

refs LIIKUNTA-495

### refactor(sports): use human readable 1-based months for season rules 

Date constructor in Javascript uses monthIndex in range 0–11 which is
unintuitive for humans. To make the code more readable convert months
from the normal 1–12 range to 0–11 range in getIsWithinRule when passing
the seasons' month values to the Date constructor.

Also:
 - move type SeasonRule to types.ts and import it from there.
 - type winterSeason and summerSeason as type SeasonRule

refs LIIKUNTA-495

### Closes

**[LIIKUNTA-495](https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-495)**

### Landing page shortcuts in **summer**
summer

### Landing page shortcuts in **winter**
winter

## Additional notes

[LIIKUNTA-495]: https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-495?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by terovirtanen** [comment]
**Hobbies-Helsinki branch is deployed to platta: https://harrastukset-pr308.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Events-Helsinki branch is deployed to platta: https://tapahtumat-pr308.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://harrastukset-pr308.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://tapahtumat-pr308.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**EVENTS GRAPHQL PROXY is deployed to platta: https://events-graphql-proxy-pr308.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**EVENTS GRAPHQL PROXY is deployed to platta: https://events-graphql-proxy-pr308.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**VENUE GRAPHQL PROXY is deployed to platta: https://venue-graphql-proxy-pr308.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Hobbies-Helsinki branch is deployed to platta: https://harrastukset-pr308.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Events-Helsinki branch is deployed to platta: https://tapahtumat-pr308.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://harrastukset-pr308.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://tapahtumat-pr308.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**EVENTS GRAPHQL PROXY is deployed to platta: https://events-graphql-proxy-pr308.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**VENUE GRAPHQL PROXY is deployed to platta: https://venue-graphql-proxy-pr308.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Sports-Helsinki branch is deployed to platta: https://liikunta-pr308.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://liikunta-pr308.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by karisal-anders** [comment]
TODO:
 - [ ] Make hobbies and events searches empty when searching with "Ulkokuntosalit" i.e. "Outdoor gyms"

**Comment by terovirtanen** [comment]
**Hobbies-Helsinki branch is deployed to platta: https://harrastukset-pr308.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://harrastukset-pr308.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**Events-Helsinki branch is deployed to platta: https://tapahtumat-pr308.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://tapahtumat-pr308.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**EVENTS GRAPHQL PROXY is deployed to platta: https://events-graphql-proxy-pr308.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**VENUE GRAPHQL PROXY is deployed to platta: https://venue-graphql-proxy-pr308.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Sports-Helsinki branch is deployed to platta: https://liikunta-pr308.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __failed__ for https://liikunta-pr308.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by terovirtanen** [comment]
**Sports-Helsinki branch is deployed to platta: https://liikunta-pr308.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://liikunta-pr308.dev.hel.ninja :laughing::tada::tada::tada:

**Review by HeikkM — APPROVED** [review]

**Comment by terovirtanen** [comment]
**Hobbies-Helsinki branch is deployed to platta: https://harrastukset-pr308.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://harrastukset-pr308.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**Events-Helsinki branch is deployed to platta: https://tapahtumat-pr308.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://tapahtumat-pr308.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**EVENTS GRAPHQL PROXY is deployed to platta: https://events-graphql-proxy-pr308.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**VENUE GRAPHQL PROXY is deployed to platta: https://venue-graphql-proxy-pr308.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Sports-Helsinki branch is deployed to platta: https://liikunta-pr308.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by karisal-anders** [comment]
Force pushed [changes](https://github.com/City-of-Helsinki/events-helsinki-monorepo/compare/9eb20ac41965e97632010eaa45e1e509fabbf7ca..b4a721089e2c529b7970e8e9c92e500bc6180ef8) which were approved by @HeikkM in a live meeting.

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://liikunta-pr308.dev.hel.ninja :laughing::tada::tada::tada:

**Pull request merged**
