### PR TITLE
LIIKUNTA-580 | fix(geolocation): fix geolocation error notification, refactor code

### PR DESCRIPTION
**Pull request by karisal-anders**
## Description

The intention is to show a geolocation error when one is trying to order the venue search
by location and geolocation use has not been allowed by the user. The geolocation
error is intended to not be auto-closing.

### fix(geolocation): fix geolocation error notification, refactor code

add:
 - GeolocationErrorNotification component and use it in BaseApp

remove:
 - showToast as unnecessary

refactoring:
 - useGeolocation's skip parameter was never used as anything else than
   skip=true so actually useGeolocation was simply the same as
   useGeolocationContext. Now making that explicit by replacing
   useGeolocation with useGeolocationContext's implementation.
 - split code to different files
 - move useGeolocation to hooks

refs LIIKUNTA-580

### Closes

[LIIKUNTA-580](https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-580)

## Screenshots

image

## Additional notes

- **Showed** the notification to the **designer** and they **approved** this compromise solution

[LIIKUNTA-580]: https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-580?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by terovirtanen** [comment]
**Events-Helsinki branch is deployed to platta: https://tapahtumat-pr528.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://tapahtumat-pr528.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**VENUE GRAPHQL PROXY is deployed to platta: https://venue-graphql-proxy-pr528.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**EVENTS GRAPHQL PROXY is deployed to platta: https://events-graphql-proxy-pr528.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Hobbies-Helsinki branch is deployed to platta: https://harrastukset-pr528.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://harrastukset-pr528.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**Sports-Helsinki branch is deployed to platta: https://liikunta-pr528.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://liikunta-pr528.dev.hel.ninja :laughing::tada::tada::tada:

**Review by melniiv — APPROVED** [review]

**Pull request merged**
