### PR TITLE
refactor: move sharelinks to common components

### PR DESCRIPTION
**Pull request by kristianjokela**
## Description
Move `ShareLinks` and its children FB, Twitter, etc. under components and refactor apps to use `ShareLinks` from there.

### CODE REVIEW

**Comment by terovirtanen** [comment]
**Events-Helsinki branch is deployed to platta: https://tapahtumat-pr163.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Hobbies-Helsinki branch is deployed to platta: https://harrastukset-pr163.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://tapahtumat-pr163.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://harrastukset-pr163.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**Sports-Helsinki branch is deployed to platta: https://liikunta-pr163.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://liikunta-pr163.dev.hel.ninja :laughing::tada::tada::tada:

**Review by melniiv — APPROVED** [review]
should we at some point refactor also all relative paths to aliases?

**Comment by kristianjokela** [comment]
> should we at some point refactor also all relative paths to aliases?

Sure, I could do some more cleaning on next PR's; I have next on the list some more components to move, so maybe after that could do some search & replace.

**Pull request merged**
