### PR TITLE
Fix a forever loop on CMS modules if an error occurs

### PR DESCRIPTION
**Pull request by nikomakela**
HH-326.

1. Move the reusable Apollo error handler init to new hook

2. The Apollo error reducer should not create a new state object
when nothing changes, or otherwise it will be dealt as a new
state in the component / provider as well.

NOTE: There is still a reloading issue in pages that uses CMS
modules like event carousels, but it won't lead to a forever loop anymore. Because of a reload the error toaster will just appear again.

### CODE REVIEW

**Comment by terovirtanen** [comment]
**Events-Helsinki branch is deployed to platta: https://tapahtumat-pr470.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Hobbies-Helsinki branch is deployed to platta: https://harrastukset-pr470.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Sports-Helsinki branch is deployed to platta: https://liikunta-pr470.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**EVENTS GRAPHQL PROXY is deployed to platta: https://events-graphql-proxy-pr470.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**VENUE GRAPHQL PROXY is deployed to platta: https://venue-graphql-proxy-pr470.dev.hel.ninja** :rocket::rocket::rocket:

**Review by karisal-anders — APPROVED** [review]

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://tapahtumat-pr470.dev.hel.ninja :laughing::tada::tada::tada:

**Pull request merged**
