### PR TITLE
LIIKUNTA-648 | fix: temporary possible fix to ssr issues

### PR DESCRIPTION
**Pull request by melniiv**
## Description
Temporary fix to SSR issues. 
1. Issue with Logo full screen -> Navigation to dynamic (the critical styles fix does not make any difference for some reason)
2. When Navigation is dynamic, then page stilL blinks, as the styles of the page content not applied in time.

Meta tags are working still in SSR, so the SRR content of course should be an improvement, but only when we fix all css issues (or HDS team does)
### Closes

**[LIIKUNTA-648](https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-648):**

## Additional notes

[LIIKUNTA-648]: https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-648?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by terovirtanen** [comment]
**Events-Helsinki branch is deployed to platta: https://tapahtumat-pr686.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Sports-Helsinki branch is deployed to platta: https://liikunta-pr686.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Hobbies-Helsinki branch is deployed to platta: https://harrastukset-pr686.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://liikunta-pr686.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://tapahtumat-pr686.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://harrastukset-pr686.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**Events-Helsinki branch is deployed to platta: https://tapahtumat-pr686.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Sports-Helsinki branch is deployed to platta: https://liikunta-pr686.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Hobbies-Helsinki branch is deployed to platta: https://harrastukset-pr686.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://tapahtumat-pr686.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://liikunta-pr686.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://harrastukset-pr686.dev.hel.ninja :laughing::tada::tada::tada:

**Review by nikomakela — APPROVED** [review]
It's a bad thing that we are dynamically loading the container component that has all the important content inside it when everything should be statically generated as HTML instead.

As talked with @melniiv, I can approve this as a temporary solutions, because this fixes issues with the meta tags and web crawling, but this dynamic loading ruins the whole idea of statically loaded SSG page.

**Pull request merged**
