### PR TITLE
LIIKUNTA-623 | fix(dockerfile): put "ARG BUILDER_FROM_IMAGE" back in Dockerfile

### PR DESCRIPTION
**Pull request by karisal-anders**
## Description

**BUILDER_FROM_IMAGE** in Platta **pipelines**:
 - [liikunta-ui-build-config.yml](https://dev.azure.com/City-of-Helsinki/liikunta/_git/liikunta-pipelines?path=%2Fdevops%2Fliikunta-ui-build-config.yml&_a=contents&version=GBmaster) sets BUILDER_FROM_IMAGE build arg to:
   - `container-registry.platta-net.hel.fi/hki-kuva-liikunta/${LIIKUNTA_CACHE_IMAGE}:latest`
 - LIIKUNTA_CACHE_IMAGE is set to:
   - `liikunta-cache-test` in [testing](https://dev.azure.com/City-of-Helsinki/liikunta/_git/liikunta-pipelines?path=%2Fvariables%2Fliikunta-variables-testing.yml&_a=contents&version=GBmaster) environment
   - `liikunta-cache-test` in [review](https://dev.azure.com/City-of-Helsinki/liikunta/_git/liikunta-pipelines?path=/variables/liikunta-variables-development.yml&_a=contents&version=GBmaster) environments
   - `liikunta-cache-staging` in [staging](https://dev.azure.com/City-of-Helsinki/liikunta/_git/liikunta-pipelines?path=%2Fvariables%2Fliikunta-variables-staging.yml&_a=contents&version=GBmaster) environment
   - `liikunta-cache-staging` in [production](https://dev.azure.com/City-of-Helsinki/liikunta/_git/liikunta-pipelines?path=%2Fvariables%2Fliikunta-variables-production.yml&_a=contents&version=GBmaster) environment

### fix(dockerfile): put "ARG BUILDER_FROM_IMAGE" back in Dockerfile

"ARG BUILDER_FROM_IMAGE" was removed in PR #638 when changing to Redhat
UBI base images in dockerfiles. It looks like the BUILDER_FROM_IMAGE is
actually being used in the CI/CD pipeline on Platta, so removing it
probably broke something in the Platta pipelines.

refs LIIKUNTA-623
refs HH-332 (PR #638 removed "ARG BUILDER_FROM_IMAGE" from Dockerfile)

### Related

[LIIKUNTA-623](https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-623)
[HH-332](https://helsinkisolutionoffice.atlassian.net/browse/HH-332)

## Additional notes

[LIIKUNTA-623]: https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-623?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[HH-332]: https://helsinkisolutionoffice.atlassian.net/browse/HH-332?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by terovirtanen** [comment]
**Hobbies-Helsinki branch is deployed to platta: https://harrastukset-pr648.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Events-Helsinki branch is deployed to platta: https://tapahtumat-pr648.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Sports-Helsinki branch is deployed to platta: https://liikunta-pr648.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://harrastukset-pr648.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://tapahtumat-pr648.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://liikunta-pr648.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**EVENTS GRAPHQL PROXY is deployed to platta: https://events-graphql-proxy-pr648.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**VENUE GRAPHQL PROXY is deployed to platta: https://venue-graphql-proxy-pr648.dev.hel.ninja** :rocket::rocket::rocket:

**Review by jakezu — APPROVED** [review]
LGFM

**Pull request merged**
