### PR TITLE
feat(sports): show venue's short description in venue detail page

### PR DESCRIPTION
**Pull request by karisal-anders**
### feat(sports): show venue's short description in venue detail page

shortDescription was added to the venue-graphql-proxy recently, so it is
now available

### CODE REVIEW

**Comment by terovirtanen** [comment]
**Sports-Helsinki branch is deployed to platta: https://liikunta-pr496.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://liikunta-pr496.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**Sports-Helsinki branch is deployed to platta: https://liikunta-pr496.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://liikunta-pr496.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by karisal-anders** [comment]
Would need to be refined if the short description would be wanted to be shown in the venue detail page. Not releasable as is.

**Pull request closed without merging**
