### PR TITLE
Breadcrumbs: implemenation to the apps 

### PR DESCRIPTION
**Pull request by nikomakela**
NOTE: Depends on router changes of https://github.com/City-of-Helsinki/events-helsinki-monorepo/pull/650 and HCRC-lib changes of https://github.com/City-of-Helsinki/react-helsinki-headless-cms/pull/165

LIIKUNTA-611.

The HDS breadcrumbs are used from HCRC-lib.

The dynamic CMS pages and the CMS articles now renders
the breadcrumbs that the CMS API offers.

The page and article query is defined in the RCHC-lib
and the RCHC-lib also takes cares of duplicates links in a list of
breadcrumbs, since there could be for example a duplicated root / home.

The common-packages package removes some excluded paths, since
the `/pages` path is not wanted to be included in the breadcrumbs.

Other features added:
- Force add the article archive list item in the breadcrumbs
of any CMS article page.
- Add breadcrumbs to article archive page
- Add breadcrumbs to search page
- Add breadcrumbs to venue details page
- Add breadcrumbs to event and course detail pages
- Add breadcrumbs to cookie consent page

----
### Desktop view of a 3rd level page

The full breadcrumb is visible

image

### Mobile view of a 3rd level page

The parent page is visible in the breadcrumb. The rest of the breadcrumbs are hidden. This feature comes from the HDS.

image

### Translations of the breadcrumbs

The translations are taken care of

image

image

image

### Article archive

The article archive has a special breadcrumbs handling because the articles does not have the breadcrumbs feature in CMS yet.

image

In Swedish

image

### Articles

The article has a special breadcrumbs handling because the articles does not have the breadcrumbs feature in CMS yet. The archive is added in the breadcrumbs manually.

image

image

### Search page

The breadcrumbs are fetched from the search cms page

image

Swedish -- the translations are taken care of

image

### Venue details

image

image

image

### Event and course details

image

Smaller view

image

Smallest view

image

in Swedish

image

### Cookie consent page

image

image

### CODE REVIEW

**Review by melniiv — APPROVED** [review]

**Comment by terovirtanen** [comment]
**Federation Router branch is deployed to platta: https://events-graphql-federation-hobbies-pr651.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Federation Router branch is deployed to platta: https://events-graphql-federation-events-pr651.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Federation Router branch is deployed to platta: https://events-graphql-federation-sports-pr651.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Events-Helsinki branch is deployed to platta: https://tapahtumat-pr651.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Sports-Helsinki branch is deployed to platta: https://liikunta-pr651.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://tapahtumat-pr651.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://liikunta-pr651.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://harrastukset-pr651.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**EVENTS GRAPHQL PROXY is deployed to platta: https://events-graphql-proxy-pr651.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**VENUE GRAPHQL PROXY is deployed to platta: https://venue-graphql-proxy-pr651.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Events-Helsinki branch is deployed to platta: https://tapahtumat-pr651.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Hobbies-Helsinki branch is deployed to platta: https://harrastukset-pr651.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Sports-Helsinki branch is deployed to platta: https://liikunta-pr651.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://tapahtumat-pr651.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://liikunta-pr651.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://harrastukset-pr651.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**VENUE GRAPHQL PROXY is deployed to platta: https://venue-graphql-proxy-pr651.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**EVENTS GRAPHQL PROXY is deployed to platta: https://events-graphql-proxy-pr651.dev.hel.ninja** :rocket::rocket::rocket:

**Pull request merged**
