### PR TITLE
Improve page revalidation logging with timestamps

### PR DESCRIPTION
**Pull request by nikomakela**
TH-1312

### CODE REVIEW

**Review by melniiv — APPROVED** [review]
LGTM

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://harrastukset-pr349.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**Events-Helsinki branch is deployed to platta: https://tapahtumat-pr349.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Sports-Helsinki branch is deployed to platta: https://liikunta-pr349.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://tapahtumat-pr349.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://liikunta-pr349.dev.hel.ninja :laughing::tada::tada::tada:

**Review by terovirtanen — APPROVED** [review]
looks good

**Pull request merged**
