### PR TITLE
Graphql next api apollo server for venues

### PR DESCRIPTION
**Pull request by nikomakela**
LIIKUNTA-336. Migrate the nextApi server from the old Liikunta repository. The idea and the code base is copied, but much changes was needed to get it all to work properly in their new monorepo environment. The old dependencies are updated. The biggest dependency change is in the Apollo-server: The old Liikunta-Helsinki uses the Apollo-server-micro -package which is now been deprecated, so it's now updated to the latest Apollo-server (v4) with Apollo-subgraph support. The Apollo-server should include all the features that the micro-server had earlier.

----
Multi-step deployment, because the current CI environment cannot handle a concurrent deployment for router and app changes:

1. Copy and migrate the Apollo-Server for Venues and Hauki data from the old deprecated Liikunte-Helsinki repo: https://github.com/City-of-Helsinki/events-helsinki-monorepo/pull/110
2. Do the Apollo Router work for the added Venue-subgraph (added in step 1): https://github.com/City-of-Helsinki/events-helsinki-monorepo/pull/109
3. Add (copy and migrate) the Venue details page when the Venue datasource is available (added in step 2): https://github.com/City-of-Helsinki/events-helsinki-monorepo/pull/108

### CODE REVIEW

**Comment by terovirtanen** [comment]
**Sports-Helsinki branch is deployed to platta: https://liikunta-110-liikunta-336-nextapi.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Events-Helsinki branch is deployed to platta: https://tapahtumat-pr110.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Hobbies-Helsinki branch is deployed to platta: https://harrastukset-pr110.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Sports-Helsinki branch is deployed to platta: https://liikunta-pr110.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Hobbies-Helsinki branch is deployed to platta: https://harrastukset-pr110.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Sports-Helsinki branch is deployed to platta: https://liikunta-pr110.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Sports-Helsinki branch is deployed to platta: https://liikunta-pr110.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Hobbies-Helsinki branch is deployed to platta: https://harrastukset-pr110.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Events-Helsinki branch is deployed to platta: https://tapahtumat-pr110.dev.hel.ninja** :rocket::rocket::rocket:

**Review by tuomas777 — APPROVED** [review]

**Comment by terovirtanen** [comment]
**Hobbies-Helsinki branch is deployed to platta: https://harrastukset-pr110.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Sports-Helsinki branch is deployed to platta: https://liikunta-pr110.dev.hel.ninja** :rocket::rocket::rocket:

**Pull request merged**
