### PR TITLE
LIIKUNTA-444 | feat(sports): add permanent redirects for campaign URLs

### PR DESCRIPTION
**Pull request by karisal-anders**
### feat(sports): add permanent redirects for campaign URLs 

refs LIIKUNTA-444
 
### refactor: remove AppConfig.showEventLocationExtraInfo as unnecessary 

refs LIIKUNTA-444 (Noticed the lint warning)
refs HH-296 (PR #235)

### Closes

**[LIIKUNTA-444](https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-444)**

### Related

**[HH-296](https://helsinkisolutionoffice.atlassian.net/browse/HH-296)**

## Additional notes

Added confluence page [liikunta.hel.fi's short campaign URL redirects](https://helsinkisolutionoffice.atlassian.net/wiki/spaces/DD/pages/8284176510/liikunta.hel.fi+s+short+campaign+URL+redirects)

[LIIKUNTA-444]: https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-444?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[HH-296]: https://helsinkisolutionoffice.atlassian.net/browse/HH-296?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by terovirtanen** [comment]
**Sports-Helsinki branch is deployed to platta: https://liikunta-pr330.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://liikunta-pr330.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**Hobbies-Helsinki branch is deployed to platta: https://harrastukset-pr330.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Sports-Helsinki branch is deployed to platta: https://liikunta-pr330.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Hobbies-Helsinki branch is deployed to platta: https://harrastukset-pr330.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Events-Helsinki branch is deployed to platta: https://tapahtumat-pr330.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Sports-Helsinki branch is deployed to platta: https://liikunta-pr330.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://liikunta-pr330.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by karisal-anders** [comment]
Something broke after I already got this working... let's see. → Draft

**Review by nikomakela — APPROVED** [review]
Looks good anyway. 👍

**Comment by terovirtanen** [comment]
**Events-Helsinki branch is deployed to platta: https://tapahtumat-pr330.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://harrastukset-pr330.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**Sports-Helsinki branch is deployed to platta: https://liikunta-pr330.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://tapahtumat-pr330.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://liikunta-pr330.dev.hel.ninja :laughing::tada::tada::tada:

**Pull request merged**
