### PR TITLE
New redirects to Liikunta and no permanent redirects

### PR DESCRIPTION
**Pull request by nikomakela**
LIIKUNTA-670 LIIKUNTA-671 LIIKUNTA-672.

1. Add new cms domain to env-example
2. Add new Vimma redirects. It replaces the Funaction, so the old Funaction should redirect to new Vimma targets too.
3. Add new Easysport redirects
4. Do not use permanent redirects (in any of the apps)

    The permanent redirects in NextJS configuration will use HTTP308. The
    `false` value uses HTTP307. HTTP308 is Permanen Redirect and HTTP307 is
    Temporary Redirect. The 308 status code which instructs clients/search
    engines to cache the redirect forever, so it's not easily configurable
    for new use.

### CODE REVIEW

**Comment by terovirtanen** [comment]
**Events-Helsinki branch is deployed to platta: https://tapahtumat-pr716.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Sports-Helsinki branch is deployed to platta: https://liikunta-pr716.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://tapahtumat-pr716.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**Hobbies-Helsinki branch is deployed to platta: https://harrastukset-pr716.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://liikunta-pr716.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://harrastukset-pr716.dev.hel.ninja :laughing::tada::tada::tada:

**Review by melniiv — APPROVED** [review]

**Pull request merged**
