### PR TITLE
chore(sports): update the RCHC-lib to fix upcoming events title issue

### PR DESCRIPTION
**Pull request by nikomakela**
LIIKUNTA-319

Relates to https://github.com/City-of-Helsinki/react-helsinki-headless-cms/pull/82

### CODE REVIEW

**Comment by nikomakela** [comment]
- [ ] Make a stable release.

**Comment by terovirtanen** [comment]
**${upper(replace(parameters.proxy,'-', ' '))} is deployed to platta: https://venue-graphql-proxy-pr187.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**${upper(replace(parameters.proxy,'-', ' '))} is deployed to platta: https://events-graphql-proxy-pr187.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by nikomakela** [comment]
✅ test: The English page now has a title (a Finnish one, when the English is not available)
image

**Comment by terovirtanen** [comment]
**Events-Helsinki branch is deployed to platta: https://tapahtumat-pr187.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Sports-Helsinki branch is deployed to platta: https://liikunta-pr187.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Hobbies-Helsinki branch is deployed to platta: https://harrastukset-pr187.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**${upper(replace(parameters.proxy,'-', ' '))} is deployed to platta: https://events-graphql-proxy-pr187.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**${upper(replace(parameters.proxy,'-', ' '))} is deployed to platta: https://venue-graphql-proxy-pr187.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://tapahtumat-pr187.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://liikunta-pr187.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://harrastukset-pr187.dev.hel.ninja :laughing::tada::tada::tada:

**Pull request merged**
