### PR TITLE
fix(locale): i18n routes rewrites

### PR DESCRIPTION
**Pull request by nikomakela**
HH-320.

Fix the Swedish UI, which was broke by the last dependency upgrade process.
The i18n routes rewrite table was needed to be built differently.
NOTE: The change affects to all 3 apps.

### CODE REVIEW

**Comment by terovirtanen** [comment]
**Sports-Helsinki branch is deployed to platta: https://liikunta-pr418.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://liikunta-pr418.dev.hel.ninja :laughing::tada::tada::tada:

**Review by karisal-anders — APPROVED** [review]
Swedish seems to work now with a little testing in https://liikunta-pr418.dev.hel.ninja/

Some things that I noticed that may or may not be related:

1. Search is doubled **in English** in the top navigation bar:
   - Leftmost "Search" points to https://liikunta-pr418.dev.hel.ninja/en/search i.e. has no trailing slash
   - The second to left "Search" points to https://liikunta-pr418.dev.hel.ninja/en/search/ i.e. has trailing slash

2. Going from root to search in Finnish uses URL https://liikunta-pr418.dev.hel.ninja/fi/search?q=&searchType=Venue i.e. `/fi/search?...` instead of `/fi/haku?...`, switching language on search page changes the URL to the latter form i.e. fully localized, choosing e.g. a sports category changes the URL to the former form i.e. not fully localized

3. Going from root to search in Swedish uses URL https://liikunta-pr418.dev.hel.ninja/sv/search?q=&searchType=Venue i.e. `/sv/search?...` instead of `/sv/sok?...`, switching language on search page changes the URL to the latter form i.e. fully localized, choosing e.g. a sports category changes the URL to the former form i.e. not fully localized

**Comment by nikomakela** [comment]
> Swedish seems to work now with a little testing in https://liikunta-pr418.dev.hel.ninja/
> 
> Some things that I noticed that may or may not be related:
> 
> 1. Search is doubled **in English** in the top navigation bar:
>    
>    * Leftmost "Search" points to https://liikunta-pr418.dev.hel.ninja/en/search i.e. has no trailing slash
>    * The second to left "Search" points to https://liikunta-pr418.dev.hel.ninja/en/search/ i.e. has trailing slash

I might self added it at some point to the test-cms for some navigation / routing testing.

> 2. Going from root to search in Finnish uses URL https://liikunta-pr418.dev.hel.ninja/fi/search?q=&searchType=Venue i.e. `/fi/search?...` instead of `/fi/haku?...`, switching language on search page changes the URL to the latter form i.e. fully localized, choosing e.g. a sports category changes the URL to the former form i.e. not fully localized
> 3. Going from root to search in Swedish uses URL https://liikunta-pr418.dev.hel.ninja/sv/search?q=&searchType=Venue i.e. `/sv/search?...` instead of `/sv/sok?...`, switching language on search page changes the URL to the latter form i.e. fully localized, choosing e.g. a sports category changes the URL to the former form i.e. not fully localized

This has been like this for long. We have tried to tackle this issue earlier, but the changes were so huge and complicated that we decided to not to do those. The problem is in the middleware-level between the CMS and App. The CMS gives us some links without knowing how to route them properly. Back then we thought that it would be too complicated to fix the issue in the middleware level. Too much pain for no actual gain.

**Pull request merged**
