### PR TITLE
LIIKUNTA-511 | chore: update unified-seach subgraph and supergraph after that

### PR DESCRIPTION
**Pull request by karisal-anders**
### chore: update unified-search subgraph and supergraph after that

what was done:
```bash
cd ./proxies/events-graphql-federation
rover subgraph introspect \
    https://kuva-unified-search.api.test.hel.ninja/search \
    > subgraphs/unified-search/unified-search.graphql
npx prettier subgraphs/unified-search/unified-search.graphql -w
rover supergraph compose --config ./supergraph-config.yaml \
    > ./supergraph.graphql
```

refs LIIKUNTA-511 (groundwork related to target group filtering)

## Issues

**[LIIKUNTA-511](https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-511)**

## Additional notes

[LIIKUNTA-511]: https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-511?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by terovirtanen** [comment]
**Federation Router branch is deployed to platta: https://events-graphql-federation-sports-pr403.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Federation Router branch is deployed to platta: https://events-graphql-federation-events-pr403.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Federation Router branch is deployed to platta: https://events-graphql-federation-sports-pr403.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Federation Router branch is deployed to platta: https://events-graphql-federation-events-pr403.dev.hel.ninja** :rocket::rocket::rocket:

**Review by melniiv — APPROVED** [review]

**Pull request merged**
