### PR TITLE
Add K6 load test to test CMS performance

### PR DESCRIPTION
**Pull request by nikomakela**
Run the tests with `k6 run k6CMSLoadTests.js `

```

❯ k6 run k6CMSLoadTests.js

          /\      |‾‾| /‾‾/   /‾‾/   
     /\  /  \     |  |/  /   /  /    
    /  \/    \    |     (   /   ‾‾\  
   /          \   |  |\  \ |  (‾)  | 
  / __________ \  |__| \__\ \_____/ .io

  execution: local
     script: k6CMSLoadTests.js
     output: -

  scenarios: (100.00%) 1 scenario, 30 max VUs, 1m0s max duration (incl. graceful stop):
           * default: 30 looping VUs for 30s (gracefulStop: 30s)


running (0m34.9s), 00/30 VUs, 153 complete and 0 interrupted iterations
default ✓ [======================================] 30 VUs  30s

     ✓ status was 200 and a page was returned

     checks.........................: 100.00% ✓ 153      ✗ 0   
     data_received..................: 619 kB  18 kB/s
     data_sent......................: 277 kB  7.9 kB/s
     http_req_blocked...............: avg=46.81ms  min=0s    med=1µs   max=355.94ms p(90)=233.62ms p(95)=286.43ms
     http_req_connecting............: avg=10.9ms   min=0s    med=0s    max=64.04ms  p(90)=54.01ms  p(95)=60.83ms 
     http_req_duration..............: avg=5.35s    min=1.76s med=5.34s max=8.78s    p(90)=6.72s    p(95)=7.12s   
       { expected_response:true }...: avg=5.35s    min=1.76s med=5.34s max=8.78s    p(90)=6.72s    p(95)=7.12s   
     http_req_failed................: 0.00%   ✓ 0        ✗ 153 
     http_req_receiving.............: avg=67.43µs  min=30µs  med=54µs  max=1.17ms   p(90)=81.2µs   p(95)=91.2µs  
     http_req_sending...............: avg=201.42µs min=79µs  med=158µs max=3.71ms   p(90)=269.4µs  p(95)=303.8µs 
     http_req_tls_handshaking.......: avg=30.49ms  min=0s    med=0s    max=265.61ms p(90)=147.16ms p(95)=202.21ms
     http_req_waiting...............: avg=5.35s    min=1.76s med=5.34s max=8.78s    p(90)=6.72s    p(95)=7.12s   
     http_reqs......................: 153     4.382984/s
     iteration_duration.............: avg=6.4s     min=2.94s med=6.36s max=10.13s   p(90)=7.84s    p(95)=8.28s   
     iterations.....................: 153     4.382984/s
     vus............................: 7       min=7      max=30
     vus_max........................: 30      min=30     max=30

```

### CODE REVIEW

**Comment by terovirtanen** [comment]
**Events-Helsinki branch is deployed to platta: https://tapahtumat-pr312.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by nikomakela** [comment]
I ran with 30 virtual users for 1 min and the CMS went down. It came back in 3 minutes.

```
running (1m11.5s), 00/30 VUs, 2247 complete and 0 interrupted iterations
default ✓ [======================================] 30 VUs  1m0s

     ✗ status was 200 and a page was returned
      ↳  0% — ✓ 0 / ✗ 2247

     checks.....................: 0.00%   ✓ 0         ✗ 2247
     data_received..............: 9.2 MB  129 kB/s
     data_sent..................: 3.8 MB  53 kB/s
     http_req_blocked...........: avg=4.25ms   min=0s      med=0s      max=497.7ms p(90)=1µs      p(95)=1µs     
     http_req_connecting........: avg=665.82µs min=0s      med=0s      max=56.25ms p(90)=0s       p(95)=0s      
     http_req_duration..........: avg=875.23ms min=43.95ms med=67.76ms max=30.2s   p(90)=104.87ms p(95)=127.46ms
     http_req_failed............: 100.00% ✓ 2247      ✗ 0   
     http_req_receiving.........: avg=154.25µs min=20µs    med=33µs    max=29.51ms p(90)=363µs    p(95)=756.99µs
     http_req_sending...........: avg=85.79µs  min=37µs    med=76µs    max=1.18ms  p(90)=112µs    p(95)=130µs   
     http_req_tls_handshaking...: avg=3.55ms   min=0s      med=0s      max=438.9ms p(90)=0s       p(95)=0s      
     http_req_waiting...........: avg=874.99ms min=43.84ms med=67.66ms max=30.2s   p(90)=104.52ms p(95)=127.14ms
     http_reqs..................: 2247    31.444985/s
     iteration_duration.........: avg=879.64ms min=44.1ms  med=67.99ms max=30.43s  p(90)=106.26ms p(95)=130.56ms
     iterations.................: 2247    31.444985/s
     vus........................: 3       min=3       max=30
     vus_max....................: 30      min=30      max=30
```

**Comment by terovirtanen** [comment]
**Hobbies-Helsinki branch is deployed to platta: https://harrastukset-pr312.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://harrastukset-pr312.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**Events-Helsinki branch is deployed to platta: https://tapahtumat-pr312.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Sports-Helsinki branch is deployed to platta: https://liikunta-pr312.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://tapahtumat-pr312.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://liikunta-pr312.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**Hobbies-Helsinki branch is deployed to platta: https://harrastukset-pr312.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Events-Helsinki branch is deployed to platta: https://tapahtumat-pr312.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://harrastukset-pr312.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://tapahtumat-pr312.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**Sports-Helsinki branch is deployed to platta: https://liikunta-pr312.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://liikunta-pr312.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**Hobbies-Helsinki branch is deployed to platta: https://harrastukset-pr312.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://harrastukset-pr312.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
## TestCafe result is __failed__ for https://tapahtumat-pr312.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by terovirtanen** [comment]
**Sports-Helsinki branch is deployed to platta: https://liikunta-pr312.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://liikunta-pr312.dev.hel.ninja :laughing::tada::tada::tada:

**Review by karisal-anders — COMMENTED** [review]
Observations/comments/ideas:
- The added files are identical except for (liikunta|harrastus|tapahtumat) word in line 132. Perhaps to reduce code duplication this functionality or e.g. `query` could be put in a shared place?
- README additions mentioning k6, [its installation](https://k6.io/docs/get-started/installation/) and how to run the related scripts would be good for maintenance as currently k6 isn't mentioned in the monorepo READMEs at all.
- If the CMS currently breaks—as it seems according to my local testing and [yours](https://github.com/City-of-Helsinki/events-helsinki-monorepo/pull/312#issuecomment-1531110608)—when run with the default options is it good to have those options as the default? Or is it that ok, these should pass ok, but currently CMS is so under resourced that it can't handle the load?

**Review by melniiv — APPROVED** [review]

**Comment by nikomakela** [comment]
> * If the CMS currently breaks—as it seems according to my local testing and [yours](https://github.com/City-of-Helsinki/events-helsinki-monorepo/pull/312#issuecomment-1531110608)—when run with the default options is it good to have those options as the default? Or is it that ok, these should pass ok, but currently CMS is so under resourced that it can't handle the load?

I would say that the default values are good: They are not huge enough to break anything when the CMS works, but they are also not so low that they don't test anything.

> * README additions mentioning k6, [its installation](https://k6.io/docs/get-started/installation/) and how to run the related scripts would be good for maintenance as currently k6 isn't mentioned in the monorepo READMEs at all.

I added just a small not about K6 in the root README. We should take it in wider use and think about documentation after that. Now it's just more like helper tool.


> The added files are identical except for (liikunta|harrastus|tapahtumat) word in line 132. Perhaps to reduce code duplication this functionality or e.g. query could be put in a shared place?

I tried to make some common code, but the problem is that the K6 script does not find the imported code. 😄 We need to configure the code base some how and I don't have time for it now.

**Comment by terovirtanen** [comment]
**Hobbies-Helsinki branch is deployed to platta: https://harrastukset-pr312.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://harrastukset-pr312.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**Events-Helsinki branch is deployed to platta: https://tapahtumat-pr312.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://liikunta-pr312.dev.hel.ninja :laughing::tada::tada::tada:

**Pull request merged**
