### PR TITLE
LIIKUNTA-556 | feat(sports): change appName to "Helsinki Liikkuu" / "Idrott och motion"

### PR DESCRIPTION
**Pull request by karisal-anders**
### feat(sports): change appName to "Helsinki Liikkuu" / "Idrott och motion"

refs LIIKUNTA-556

### Closes

**[LIIKUNTA-556](https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-556)**

## Additional notes

[LIIKUNTA-556]: https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-556?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by terovirtanen** [comment]
**Hobbies-Helsinki branch is deployed to platta: https://harrastukset-pr479.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Events-Helsinki branch is deployed to platta: https://tapahtumat-pr479.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Sports-Helsinki branch is deployed to platta: https://liikunta-pr479.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://tapahtumat-pr479.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**VENUE GRAPHQL PROXY is deployed to platta: https://venue-graphql-proxy-pr479.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://liikunta-pr479.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**EVENTS GRAPHQL PROXY is deployed to platta: https://events-graphql-proxy-pr479.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __failed__ for https://harrastukset-pr479.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Review by nikomakela — APPROVED** [review]

**Pull request merged**
