### PR TITLE
Change docker image to the Node 20 UBI-image

### PR DESCRIPTION
**Pull request by nikomakela**
LIIKUNTA-624.
Add documentation of how to use the docker composer locally with the cached image. Add some missing arguments to the docker composer build time arguments. Added the `esbuild` dependency to fix local docker builds.

(Try to) redo (better 😄 ) what was reverted here in https://github.com/City-of-Helsinki/events-helsinki-monorepo/pull/649/.

### CODE REVIEW

**Comment by terovirtanen** [comment]
**EVENTS GRAPHQL PROXY is deployed to platta: https://events-graphql-proxy-pr653.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**VENUE GRAPHQL PROXY is deployed to platta: https://venue-graphql-proxy-pr653.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by karisal-anders** [comment]
Diff between main just before reverting last UBI image changes and this branch:

https://github.com/City-of-Helsinki/events-helsinki-monorepo/compare/e5c8c03152a37edc920728c6c32911787c7ffe72...LIIKUNTA-624-docker-image-update

**Comment by karisal-anders** [comment]
> Diff between main just before reverting last UBI image changes and this branch:
> 
> [e5c8c03...LIIKUNTA-624-docker-image-update](https://github.com/City-of-Helsinki/events-helsinki-monorepo/compare/e5c8c03152a37edc920728c6c32911787c7ffe72...LIIKUNTA-624-docker-image-update)

According to this `proxy.Dockerfile` is still using helsinkitest image.

**Comment by terovirtanen** [comment]
**VENUE GRAPHQL PROXY is deployed to platta: https://venue-graphql-proxy-pr653.dev.hel.ninja** :rocket::rocket::rocket:

**Review by karisal-anders — APPROVED** [review]
Looks ok to me, we need to test this in the CI/CD pipelines though so they work too!

**Comment by nikomakela** [comment]
> Looks ok to me, we need to test this in the CI/CD pipelines though so they work too!

Yep, I've been trying to find a solution how to update the base image of the CI-pipeline. It's not a simple thing, since the pipeline configuration of the baser image creation cannot be overridden any how. 😞 This leads to a situation, that the base image would use the old "Helsinki-test-image", but the app-build would use the ubi-image (that would then base on the helsinki-test-image). I think there are 3 different approaches to fix this:
1. Delete the cache image so it would be recreated properly. The problem with this is that no-one I know has privileges to do that (and it should be done with some terminal tools).
2. Disable the cache image usage for while and re-enable it once all the images are using the UBI. I'm not sure whether or not we would still have the issue when re-enabling it.
3. Merge this so that the cache-image can be forced to use the ubi-images only, because the cache-image pipeline is using app's master branch (and we cannot change it).

I will now try the 2nd and 3rd approaches: if the 2nd does not work, I'll continue with the 3rd.

**Comment by terovirtanen** [comment]
**Events-Helsinki branch is deployed to platta: https://tapahtumat-pr653.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://liikunta-pr653.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://harrastukset-pr653.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**VENUE GRAPHQL PROXY is deployed to platta: https://venue-graphql-proxy-pr653.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://tapahtumat-pr653.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**EVENTS GRAPHQL PROXY is deployed to platta: https://events-graphql-proxy-pr653.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**EVENTS GRAPHQL PROXY is deployed to platta: https://events-graphql-proxy-pr653.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**VENUE GRAPHQL PROXY is deployed to platta: https://venue-graphql-proxy-pr653.dev.hel.ninja** :rocket::rocket::rocket:

**Pull request merged**
