### PR TITLE
chore: update content on pod

### PR DESCRIPTION
**Pull request by terovirtanen**
## Description
Investigate permission issue on content update

Add review and release pipelines for federation router. 

## Issues
Failure on platta : 

> 5:34:58 AM [info] [general] - Allowing unauthorized requests
> Failed to update prerender cache for /fi [Error: EACCES: permission denied, open '/app/apps/hobbies-helsinki/.next/server/pages/fi.html'] {
> errno: -13,
> code: 'EACCES',
> syscall: 'open',
> path: '/app/apps/hobbies-helsinki/.next/server/pages/fi.html'
> }
>

### CODE REVIEW

**Comment by terovirtanen** [comment]
**Hobbies-Helsinki branch is deployed to platta: harrastukset-merge.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Hobbies-Helsinki branch is deployed to platta: https://harrastukset-85-update-content.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Hobbies-Helsinki branch is deployed to platta: https://harrastukset-85-update-content.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Hobbies-Helsinki branch is deployed to platta: https://harrastukset-85-update-content.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Hobbies-Helsinki branch is deployed to platta: https://harrastukset-85-update-content.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Hobbies-Helsinki branch is deployed to platta: https://harrastukset-85-update-content.dev.hel.ninja** :rocket::rocket::rocket:

**Review by nikomakela — APPROVED** [review]
I don't know if the folder really includes all the necessary stuff, but without bigger investigation, looks good to me.

**Pull request merged**
