### PR TITLE
fix: sports categories shortcuts

### PR DESCRIPTION
**Pull request by melniiv**
## Description
Fix sport categories shortcuts url

### Closes

**[DEV-XXX](https://helsinkisolutionoffice.atlassian.net/browse/DEV-XXX):**

### CODE REVIEW

**Review by nikomakela — APPROVED** [review]

**Comment by terovirtanen** [comment]
**Sports-Helsinki branch is deployed to platta: https://liikunta-pr254.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by nikomakela** [comment]
Could this have a link to a filter field instead? It would be easier to notice the attribute changes

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://liikunta-pr254.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**Sports-Helsinki branch is deployed to platta: https://liikunta-pr254.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://liikunta-pr254.dev.hel.ninja :laughing::tada::tada::tada:

**Pull request merged**
