### PR TITLE
Refactor the badly working error boundary implementation for the GraphQL errors

### PR DESCRIPTION
**Pull request by nikomakela**
HH-309

The old version of the GraphQL error handling works with the ErrorBoundary implementation. There is an issue between the NextJS and the NextJS-i18next, which makes it some what impossible to use translations in the generic error page. The i18next translations needs the getStaticServerSideProps method for the static pages in order to full fill the need of the translations, but the 500-page and the custom nextjs-error-page (_error.tsx) does not fully support the getStaticServerSideProps. This implementation is also a compromise and it might mean that the error page will blink without the translations, but the final page where the user is taken, should include all the translation (at least it was tested so). Instead of full error page, the graphql-errors are now shown in a HDS notification toaster / modal window.

The most critical change to the old is that the graphqlerrors does no longer have a "soft handling" when the server side error occures. Earlier, the graphql errors had their own code block that did catch the thrown error and rendered a page with `status: 500` & `revalidation: 1`. Instead of this, the error is now thrown, which makes the failing revalidation to be totally ignored and the old version will persist. For the user this looks much better.

The network connections issues can be tested with a local Apollo router and `traffic_shaping` -configuration. With those configs a developer can set a rate limit for handled requests. An example is added in the `router.yaml`.

*It should be noted, that there must be some static pages like front page, search page, article archive page, 404 and 500 generated in a build time!* This is the only way offer error pages and nice looking root pages to the user. The pages have menus and links that are fetched from the CMS, so the CMS connection must be established on build time. However, now when we are revalidating the pages on-demand (instead of automatic revalidation), the build does only need ~5 simple pages (for every supported language), so the build time page generation should be quite fast.

*NOTE: this branch is based on a branch that updated the dependencies (and is not directly based on main-branch)* https://github.com/City-of-Helsinki/events-helsinki-monorepo/pull/367

### CODE REVIEW

**Review by melniiv — APPROVED** [review]

**Review by HeikkM — APPROVED** [review]

**Comment by terovirtanen** [comment]
**Federation Router branch is deployed to platta: https://events-graphql-federation-hobbies-pr373.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Federation Router branch is deployed to platta: https://events-graphql-federation-sports-pr373.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Federation Router branch is deployed to platta: https://events-graphql-federation-events-pr373.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Events-Helsinki branch is deployed to platta: https://tapahtumat-pr373.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Sports-Helsinki branch is deployed to platta: https://liikunta-pr373.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://tapahtumat-pr373.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://liikunta-pr373.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**EVENTS GRAPHQL PROXY is deployed to platta: https://events-graphql-proxy-pr373.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**VENUE GRAPHQL PROXY is deployed to platta: https://venue-graphql-proxy-pr373.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Federation Router branch is deployed to platta: https://events-graphql-federation-hobbies-pr373.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Federation Router branch is deployed to platta: https://events-graphql-federation-sports-pr373.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Federation Router branch is deployed to platta: https://events-graphql-federation-events-pr373.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Hobbies-Helsinki branch is deployed to platta: https://harrastukset-pr373.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Events-Helsinki branch is deployed to platta: https://tapahtumat-pr373.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Sports-Helsinki branch is deployed to platta: https://liikunta-pr373.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://harrastukset-pr373.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://tapahtumat-pr373.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**EVENTS GRAPHQL PROXY is deployed to platta: https://events-graphql-proxy-pr373.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**VENUE GRAPHQL PROXY is deployed to platta: https://venue-graphql-proxy-pr373.dev.hel.ninja** :rocket::rocket::rocket:

**Pull request merged**
