### PR TITLE
LIIKUNTA-582, LIIKUNTA-585 | feat: add support for hierarchical menus & universal bar menu in header

### PR DESCRIPTION
**Pull request by karisal-anders**
### feat: add support for hierarchical menus & universal bar menu in header

refs LIIKUNTA-582 (add support for hierarchical menus in header)
refs LIIKUNTA-585 (add support for universal bar menu in header)

### Closes

[LIIKUNTA-582](https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-582)
[LIIKUNTA-585](https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-585)

## Testing

 - Check out PR's branch locally
 - `yarn`
 - `cd apps/sports-helsinki`
   - set local variables in `.env.local`
     - NEXT_PUBLIC_CMS_HEADER_UNIVERSAL_BAR_MENU_NAME_FI="Sports Helsinki Universal bar FI"
     - NEXT_PUBLIC_CMS_HEADER_UNIVERSAL_BAR_MENU_NAME_EN="Sports Helsinki Universal bar EN"
     - NEXT_PUBLIC_CMS_HEADER_UNIVERSAL_BAR_MENU_NAME_SV="Sports Helsinki Universal bar SV"
   - `yarn dev`

## Screenshots

image

image

image

image

image

image

image

image

## Additional notes

[LIIKUNTA-582]: https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-582?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LIIKUNTA-585]: https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-585?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by terovirtanen** [comment]
**VENUE GRAPHQL PROXY is deployed to platta: https://venue-graphql-proxy-pr552.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**EVENTS GRAPHQL PROXY is deployed to platta: https://events-graphql-proxy-pr552.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Sports-Helsinki branch is deployed to platta: https://liikunta-pr552.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://liikunta-pr552.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**EVENTS GRAPHQL PROXY is deployed to platta: https://events-graphql-proxy-pr552.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**VENUE GRAPHQL PROXY is deployed to platta: https://venue-graphql-proxy-pr552.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Events-Helsinki branch is deployed to platta: https://tapahtumat-pr552.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://tapahtumat-pr552.dev.hel.ninja :laughing::tada::tada::tada:

**Review by melniiv — APPROVED** [review]

**Comment by terovirtanen** [comment]
**Sports-Helsinki branch is deployed to platta: https://liikunta-pr552.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://tapahtumat-pr552.dev.hel.ninja :laughing::tada::tada::tada:

**Pull request merged**
