### PR TITLE
Revert "Add critical-hds-styles to a new file imported in global styles"

### PR DESCRIPTION
**Pull request by nikomakela**
LIIKUNTA-612 HH-311 HH-335.

Reverts City-of-Helsinki/events-helsinki-monorepo#615 changes that were related to the refactoring how the critical HDS styles were applied.

### CODE REVIEW

**Comment by terovirtanen** [comment]
**Hobbies-Helsinki branch is deployed to platta: https://harrastukset-pr630.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Events-Helsinki branch is deployed to platta: https://tapahtumat-pr630.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Sports-Helsinki branch is deployed to platta: https://liikunta-pr630.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://harrastukset-pr630.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://tapahtumat-pr630.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://liikunta-pr630.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**VENUE GRAPHQL PROXY is deployed to platta: https://venue-graphql-proxy-pr630.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**EVENTS GRAPHQL PROXY is deployed to platta: https://events-graphql-proxy-pr630.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by nikomakela** [comment]
LEft in draft mode only to make it less important for now. The reverting commits should still be good.

**Comment by nikomakela** [comment]
Closing: Used the approach of the https://github.com/City-of-Helsinki/events-helsinki-monorepo/pull/632 instead.

**Pull request closed without merging**
