### PR TITLE
Alternative solution to refactor the common components by moving them them in components-package

### PR DESCRIPTION
**Pull request by nikomakela**
LIIKUNTA-474

Alternative for #372, where there were tests missing, some conflicting type definitions and intense prop drilling _with huge objects_ that are really hard to mock. The starting point for making this alternative pull request has been to take care of the tests while the code has been moved, so that fixing the tests would be more systematic and the quality can be proved. 2nd most important idea has been to add as few and as small as possible new properties to the components, so that they would be easy to mock and easy to test and they would not make the component too heavy or to rerender too often.

This pull request should be continued so that the props drilling is refactored with some React context implementations. I think that it is clear that we could have serious use for 2 new providers:
1. theme provider, to style buttons
2. application specific common routing handlers provider, to prevent intense prop drilling through various common components.

### CODE REVIEW

**Comment by terovirtanen** [comment]
**Hobbies-Helsinki branch is deployed to platta: https://harrastukset-pr390.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Events-Helsinki branch is deployed to platta: https://tapahtumat-pr390.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Sports-Helsinki branch is deployed to platta: https://liikunta-pr390.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://harrastukset-pr390.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://tapahtumat-pr390.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://liikunta-pr390.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**VENUE GRAPHQL PROXY is deployed to platta: https://venue-graphql-proxy-pr390.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**EVENTS GRAPHQL PROXY is deployed to platta: https://events-graphql-proxy-pr390.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Hobbies-Helsinki branch is deployed to platta: https://harrastukset-pr390.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Events-Helsinki branch is deployed to platta: https://tapahtumat-pr390.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Sports-Helsinki branch is deployed to platta: https://liikunta-pr390.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://harrastukset-pr390.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**VENUE GRAPHQL PROXY is deployed to platta: https://venue-graphql-proxy-pr390.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**EVENTS GRAPHQL PROXY is deployed to platta: https://events-graphql-proxy-pr390.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by melniiv** [comment]
I am not sure that theme provider will fix the issue. The problem is that HDS components theming is inconsistent. I think the theme provider should be on the HDS level in general. In some component they have theme property, in some, in addition, they have variant. In some, there are none of those and the only way to style them is either overriding the scss variables either with  custom classNames (check the CheckBox implementation). Also problem on top is that sometimes we have buttons which are not in any theme or variant, for example Yellow background primary buttons. A lot of things to consider.
Otherwise PR looks like a good refactoring start!

**Review by melniiv — APPROVED** [review]

**Pull request merged**
