### PR TITLE
LIIKUNTA-606 | fix: unknown error page's link text translations (fi & sv were swapped)

### PR DESCRIPTION
**Pull request by karisal-anders**
### fix: unknown error page's link text translations (fi & sv were swapped)

refs LIIKUNTA-606

### Related

[LIIKUNTA-606](https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-606)

## Additional notes

[LIIKUNTA-606]: https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-606?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by terovirtanen** [comment]
**Hobbies-Helsinki branch is deployed to platta: https://harrastukset-pr629.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Events-Helsinki branch is deployed to platta: https://tapahtumat-pr629.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Sports-Helsinki branch is deployed to platta: https://liikunta-pr629.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://harrastukset-pr629.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://liikunta-pr629.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**VENUE GRAPHQL PROXY is deployed to platta: https://venue-graphql-proxy-pr629.dev.hel.ninja** :rocket::rocket::rocket:

**Review by jannetalvio — APPROVED** [review]

**Pull request merged**
