### PR TITLE
TH-1258 | Remove age filter from events-helsinki's advanced search

### PR DESCRIPTION
**Pull request by karisal-anders**
## Description

Remove age filter from events-helsinki's advanced search and rearrange its UI elements.

### Closes

**[TH-1258](https://helsinkisolutionoffice.atlassian.net/browse/TH-1258)**

### CODE REVIEW

**Comment by karisal-anders** [comment]
Noticed the empty space being left in the advanced search UI by the removal of the age filter. Going to fix that...

**Comment by karisal-anders** [comment]
Now ready for code review. Please could one of you @nikomakela, @melniiv, @nenonja or @tuomas777 code review this pull request? Thank you!

**Review by nenonja — APPROVED** [review]
LGTM

**Review by nikomakela — APPROVED** [review]

**Comment by tuomas777** [comment]
https://github.com/City-of-Helsinki/events-helsinki-monorepo/blob/f4c3a1207037e572d202ceb8796bc8d95b76df6d/apps/events-helsinki/src/domain/search/eventSearch/constants.tsx#L107-L108

I guess these could be removed now?

**Comment by karisal-anders** [comment]
> https://github.com/City-of-Helsinki/events-helsinki-monorepo/blob/f4c3a1207037e572d202ceb8796bc8d95b76df6d/apps/events-helsinki/src/domain/search/eventSearch/constants.tsx#L107-L108
> 
> I guess these could be removed now?

Probably yes, I chose to merge this pull request to get things rolling. Made a ticket [TH-1274](https://helsinkisolutionoffice.atlassian.net/browse/TH-1274) about the cleaning up of the obsolete age filter related variables & functionality.

**Comment by karisal-anders** [comment]
> > https://github.com/City-of-Helsinki/events-helsinki-monorepo/blob/f4c3a1207037e572d202ceb8796bc8d95b76df6d/apps/events-helsinki/src/domain/search/eventSearch/constants.tsx#L107-L108
> > 
> > I guess these could be removed now?
> 
> Probably yes, I chose to merge this pull request to get things rolling. Made a ticket [TH-1274](https://helsinkisolutionoffice.atlassian.net/browse/TH-1274) about the cleaning up of the obsolete age filter related variables & functionality.

Actually this might not be necessary as there's [TH-1259](https://helsinkisolutionoffice.atlassian.net/browse/TH-1259) ("Add search filter to include or exclude Events for Children") which [TH-1258](https://helsinkisolutionoffice.atlassian.net/browse/TH-1258) mentions that will be included: "Side note: Events for children filter will be included [TH-1259](https://helsinkisolutionoffice.atlassian.net/browse/TH-1259)".

**Pull request merged**
