### PR TITLE
feat: false structured events can be ignored by using http-headers

### PR DESCRIPTION
**Pull request by nikomakela**
HH-325.

The LinkedEvents has some false structured event objects that we would like to filter out when fetching a list of events, just to make the client more fail tolerant. It should be noted that the actual issues are in the data of the LinkedEvents, but this way the fix can be delivered faster.

A new custom ignorable Graphql-error type was created. The ignorability means that the error throwing can be skipped if the request contains a custom "X-Ignored-Error-Code" header and the error code is set there as a value.

**With this kind of solution, it's not the server that makes the decision that the errors are ignored, but the client!**

----

When the `X-Ignored-Error-Code` header is not set, the EventList query fails with a new code `"UNPOPULATED_MANDATORY_DATA"`. **Note the newly given "note" -field in the response extensions, that gives a hint that the error could be ignored!**. Since the request handler throws a graphql error, there is no data included in the response.

image

When the `X-Ignored-Error-Code` header is set to have a value of `"UNPOPULATED_MANDATORY_DATA"`, the response gives the data.

image

There are warnings and console logs written to the console

image

Example of the broken query (change the host to match your server):

```
curl --request POST \
    --header 'content-type: application/json' \
    --header 'Accept-Language: fi' \
    --header 'X-Ignored-Error-Code: UNPOPULATED_MANDATORY_DATA' \
    --url http://localhost:4100/proxy/graphql \
    --data '{"query":"query EventList($audienceMaxAgeGt: String, $audienceMinAgeLt: String, $eventType: [EventTypeId], $internetBased: Boolean, $suitableFor: [Int], $allOngoing: Boolean, $allOngoingAnd: [String], $division: [String], $end: String, $endsAfter: String, $endsBefore: String, $inLanguage: String, $include: [String], $isFree: Boolean, $keyword: [String], $keywordAnd: [String], $keywordOrSet1: [String], $keywordOrSet2: [String], $keywordOrSet3: [String], $keywordNot: [String], $language: String, $localOngoingAnd: [String], $location: [String], $page: Int, $pageSize: Int, $publisher: ID, $publisherAncestor: ID, $sort: String, $start: String, $startsAfter: String, $startsBefore: String, $superEvent: ID, $superEventType: [String], $text: String, $translation: String) {\n  eventList(\n    audienceMaxAgeGt: $audienceMaxAgeGt\n    audienceMinAgeLt: $audienceMinAgeLt\n    eventType: $eventType\n    internetBased: $internetBased\n    suitableFor: $suitableFor\n    allOngoing: $allOngoing\n    allOngoingAnd: $allOngoingAnd\n    division: $division\n    end: $end\n    endsAfter: $endsAfter\n    endsBefore: $endsBefore\n    include: $include\n    inLanguage: $inLanguage\n    isFree: $isFree\n    keyword: $keyword\n    keywordAnd: $keywordAnd\n    keywordOrSet1: $keywordOrSet1\n    keywordOrSet2: $keywordOrSet2\n    keywordOrSet3: $keywordOrSet3\n    keywordNot: $keywordNot\n    language: $language\n    localOngoingAnd: $localOngoingAnd\n    location: $location\n    page: $page\n    pageSize: $pageSize\n    publisher: $publisher\n    publisherAncestor: $publisherAncestor\n    sort: $sort\n    start: $start\n    startsAfter: $startsAfter\n    startsBefore: $startsBefore\n    superEvent: $superEvent\n    superEventType: $superEventType\n    text: $text\n    translation: $translation\n  ) {\n    meta {\n      count\n      next\n      previous\n      __typename\n    }\n    data {\n      ...eventFields\n      __typename\n    }\n    __typename\n  }\n}\n\nfragment eventFields on EventDetails {\n  audienceMinAge\n  audienceMaxAge\n  id\n  eventStatus\n  externalLinks {\n    name\n    link\n    __typename\n  }\n  images {\n    id\n    name\n    url\n    photographerName\n    __typename\n  }\n  subEvents {\n    internalId\n    __typename\n  }\n  typeId\n  superEvent {\n    internalId\n    __typename\n  }\n  inLanguage {\n    name {\n      ...localizedFields\n      __typename\n    }\n    __typename\n  }\n  keywords {\n    ...keywordFields\n    __typename\n  }\n  location {\n    ...placeFields\n    __typename\n  }\n  offers {\n    ...offerFields\n    __typename\n  }\n  name {\n    ...localizedFields\n    __typename\n  }\n  description {\n    ...localizedFields\n    __typename\n  }\n  shortDescription {\n    ...localizedFields\n    __typename\n  }\n  endTime\n  startTime\n  publisher\n  provider {\n    ...localizedFields\n    __typename\n  }\n  infoUrl {\n    ...localizedFields\n    __typename\n  }\n  audience {\n    id\n    name {\n      ...localizedFields\n      __typename\n    }\n    __typename\n  }\n  locationExtraInfo {\n    ...localizedFields\n    __typename\n  }\n  enrolmentStartTime\n  enrolmentEndTime\n  remainingAttendeeCapacity\n  __typename\n}\n\nfragment localizedFields on LocalizedObject {\n  en\n  fi\n  sv\n  __typename\n}\n\nfragment keywordFields on Keyword {\n  id\n  internalId\n  dataSource\n  hasUpcomingEvents\n  name {\n    fi\n    sv\n    en\n    __typename\n  }\n  __typename\n}\n\nfragment placeFields on Place {\n  id\n  divisions {\n    type\n    name {\n      fi\n      sv\n      en\n      __typename\n    }\n    __typename\n  }\n  hasUpcomingEvents\n  internalId\n  email\n  infoUrl {\n    fi\n    sv\n    en\n    __typename\n  }\n  name {\n    fi\n    en\n    sv\n    __typename\n  }\n  addressLocality {\n    fi\n    sv\n    en\n    __typename\n  }\n  streetAddress {\n    fi\n    sv\n    en\n    __typename\n  }\n  postalCode\n  position {\n    coordinates\n    __typename\n  }\n  telephone {\n    fi\n    sv\n    en\n    __typename\n  }\n  __typename\n}\n\nfragment offerFields on Offer {\n  isFree\n  price {\n    ...localizedFields\n    __typename\n  }\n  description {\n    ...localizedFields\n    __typename\n  }\n  infoUrl {\n    ...localizedFields\n    __typename\n  }\n  __typename\n}","variables":{"allOngoing":true,"end":"","include":["keywords","location"],"keywordOrSet2":[],"keywordAnd":[],"keywordNot":[],"location":["tprek:7254"],"pageSize":10,"publisher":null,"sort":"end_time","start":"now","superEventType":["umbrella","none"],"eventType":["General"]}}'
```

### CODE REVIEW

**Comment by terovirtanen** [comment]
**Hobbies-Helsinki branch is deployed to platta: https://harrastukset-pr456.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Events-Helsinki branch is deployed to platta: https://tapahtumat-pr456.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Sports-Helsinki branch is deployed to platta: https://liikunta-pr456.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __failed__ for https://harrastukset-pr456.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://liikunta-pr456.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
## TestCafe result is __failed__ for https://tapahtumat-pr456.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by terovirtanen** [comment]
**VENUE GRAPHQL PROXY is deployed to platta: https://venue-graphql-proxy-pr456.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**EVENTS GRAPHQL PROXY is deployed to platta: https://events-graphql-proxy-pr456.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Hobbies-Helsinki branch is deployed to platta: https://harrastukset-pr456.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Events-Helsinki branch is deployed to platta: https://tapahtumat-pr456.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Sports-Helsinki branch is deployed to platta: https://liikunta-pr456.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Hobbies-Helsinki branch is deployed to platta: https://harrastukset-pr456.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Events-Helsinki branch is deployed to platta: https://tapahtumat-pr456.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Sports-Helsinki branch is deployed to platta: https://liikunta-pr456.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**EVENTS GRAPHQL PROXY is deployed to platta: https://events-graphql-proxy-pr456.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __failed__ for https://harrastukset-pr456.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by terovirtanen** [comment]
## TestCafe result is __failed__ for https://tapahtumat-pr456.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by terovirtanen** [comment]
**VENUE GRAPHQL PROXY is deployed to platta: https://venue-graphql-proxy-pr456.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://liikunta-pr456.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by nikomakela** [comment]
The docs related to this events-grapql-proxy are badly out of date and in a bad shape. There could be another pull request to update those and add some notes about this new feature there as well.

- [ ] Update the readme file

**Review by karisal-anders — APPROVED** [review]

**Comment by terovirtanen** [comment]
**Events-Helsinki branch is deployed to platta: https://tapahtumat-pr456.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Hobbies-Helsinki branch is deployed to platta: https://harrastukset-pr456.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Sports-Helsinki branch is deployed to platta: https://liikunta-pr456.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by nikomakela** [comment]
The tests fails because the variables has been removed from the infra

**Comment by terovirtanen** [comment]
## TestCafe result is __failed__ for https://tapahtumat-pr456.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://liikunta-pr456.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
## TestCafe result is __failed__ for https://harrastukset-pr456.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by terovirtanen** [comment]
**VENUE GRAPHQL PROXY is deployed to platta: https://venue-graphql-proxy-pr456.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**EVENTS GRAPHQL PROXY is deployed to platta: https://events-graphql-proxy-pr456.dev.hel.ninja** :rocket::rocket::rocket:

**Pull request merged**
