### PR TITLE
chore: remove github workflows

### PR DESCRIPTION
**Pull request by terovirtanen**
## Description
Removed pipeline actions are done on Azure DevOps pipeline templates and are run as part of review (triggered by github PR) and test (triggered by commit to main branch) pipelines. For example this pr has triggered the tests. 

build & check-dist are part of static checks
[harrastukset static tests](https://dev.azure.com/City-of-Helsinki/harrastukset/_git/harrastukset-pipelines?path=/pipeline-templates/build-pipeline-statictest.yml)
[tapahtumat static tests](https://dev.azure.com/City-of-Helsinki/tapahtumat/_git/tapahtumat-pipelines?path=/pipeline-templates/build-pipeline-statictest.yml)
[liikunta static tests](https://dev.azure.com/City-of-Helsinki/liikunta/_git/liikunta-pipelines?path=/pipeline-templates/build-pipeline-statictest.yml)

typecheck, lint & unittest are part of sonarcloud 
[harrastukset sonarcloud](https://dev.azure.com/City-of-Helsinki/harrastukset/_git/harrastukset-pipelines?path=/pipeline-templates/build-pipeline-sonarcloud.yml)
[tapahtumat sonarcloud](https://dev.azure.com/City-of-Helsinki/tapahtumat/_git/tapahtumat-pipelines?path=/pipeline-templates/build-pipeline-sonarcloud.yml)
[liikunta sonarcloud](https://dev.azure.com/City-of-Helsinki/liikunta/_git/liikunta-pipelines?path=/pipeline-templates/build-pipeline-sonarcloud.yml)

browser tests 
[harrastukset browser tests](https://dev.azure.com/City-of-Helsinki/harrastukset/_git/harrastukset-pipelines?path=/pipeline-templates/deploy-pipeline-browsertest.yml)
[tapahtumat browser tests](https://dev.azure.com/City-of-Helsinki/tapahtumat/_git/tapahtumat-pipelines?path=/pipeline-templates/deploy-pipeline-browsertest.yml)
[liikunta browser tests](https://dev.azure.com/City-of-Helsinki/liikunta/_git/liikunta-pipelines?path=/pipeline-templates/deploy-pipeline-browsertest.yml)

### Closes

**[DEVOPS-480](https://helsinkisolutionoffice.atlassian.net/browse/DEVOPS-480):**

## Additional notes

[DEVOPS-480]: https://helsinkisolutionoffice.atlassian.net/browse/DEVOPS-480?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://harrastukset-pr153.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**Federation Router branch is deployed to platta: https://events-graphql-federation-events-pr153.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Federation Router branch is deployed to platta: https://events-graphql-federation-hobbies-pr153.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Events-Helsinki branch is deployed to platta: https://tapahtumat-pr153.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Federation Router branch is deployed to platta: https://events-graphql-federation-hobbies-pr153.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Federation Router branch is deployed to platta: https://events-graphql-federation-sports-pr153.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Federation Router branch is deployed to platta: https://events-graphql-federation-events-pr153.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Events-Helsinki branch is deployed to platta: https://tapahtumat-pr153.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Sports-Helsinki branch is deployed to platta: https://liikunta-pr153.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Hobbies-Helsinki branch is deployed to platta: https://harrastukset-pr153.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://liikunta-pr153.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://tapahtumat-pr153.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://harrastukset-pr153.dev.hel.ninja :laughing::tada::tada::tada:

**Review by kristianjokela — APPROVED** [review]

**Pull request merged**
