### PR TITLE
fix: back button moves back twice when opening map

### PR DESCRIPTION
**Pull request by PekkaKela**
### Closes

**[DEV-XXX](https://helsinkisolutionoffice.atlassian.net/browse/DEV-XXX):**

## Additional notes

Was easier than anticipated. Router push fixed the problem.

### CODE REVIEW

**Comment by terovirtanen** [comment]
**Sports-Helsinki branch is deployed to platta: https://liikunta-pr290.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://liikunta-pr290.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by karisal-anders** [comment]
@PekkaKela It would be nice to have the review environment up and running to be able to test this easily. Maybe rerunning the deployment action might set it up again after having been purged during the weekend? Or just otherwise fiddling with the branch to make the pipeline trigger again.

**Comment by PekkaKela** [comment]
@karisal-anders Committed a comment to trigger pipeline and review environment to be build.

**Comment by terovirtanen** [comment]
**Sports-Helsinki branch is deployed to platta: https://liikunta-pr290.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://liikunta-pr290.dev.hel.ninja :laughing::tada::tada::tada:

**Review by karisal-anders — APPROVED** [review]
👌 P.S. All the tests pass now, so you can just drop the *comment-only* commit bf5e6852fe41d27078f4087b88ba99a0efb20238 and merge right away after that without having to recheck the CI tests IMHO.

**Comment by terovirtanen** [comment]
**Sports-Helsinki branch is deployed to platta: https://liikunta-pr290.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://liikunta-pr290.dev.hel.ninja :laughing::tada::tada::tada:

**Review by nikomakela — COMMENTED** [review]
Should the "Show on map" -button and "show on list" -button always use the push instead of replace. Now if you 
1. first navigate to the map view by clicking "show on map"
2. then click "show on a list"
3. then if you try to go back, it's a never ending loop and the user is not taken back to the map view.

It's very frustrating especially when using a phone.

image

**Comment by PekkaKela** [comment]
> Should the "Show on map" -button and "show on list" -button always use the push instead of replace. Now if you
> 
> 1. first navigate to the map view by clicking "show on map"
> 2. then click "show on a list"
> 3. then if you try to go back, it's a never ending loop and the user is not taken back to the map view.
> 
> It's very frustrating especially when using a phone.

Or should the "show on list" button be replaced? In the code there is this comment:

`/**
 * @deprecated There should be no need for List-mode,
 * because its content comes totally from a whole different component.
 */`

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://liikunta-pr290.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by nikomakela** [comment]
> Or should the "show on list" button be deleted? In the code there is this comment:
> 
> >

That's a tail from the old implementation. There was a different kind of state management that handled the active view earlier. The deprecation note is there to remove anything that is left from that. We do want the map view and we do want the list view and there are new designs for those too. Just the old way to handle it should still be removed, but that's not anything urgent.

> I changed the replace to push in map view aswell.

Yea, good! It works much better now. Good job! 👏

**Review by nikomakela — APPROVED** [review]

**Pull request merged**
