### PR TITLE
Add critical-hds-styles to a new file imported in global styles

### PR DESCRIPTION
**Pull request by nikomakela**
HH-311 HH-335

Add a new critical HDS styles file and import it in globals.

DISCLAIMER: I'm not sure whether or not this pull request should be merged. I have not been able to test all styles of al lthe apps. Since we are not using the tools that the HDS provides on every Document-component rendering, we need to manually maintain the new critical CSS styles -file. More about this https://hds.hel.fi/foundation/guidelines/server-side-rendering/#option-2-use-indexcss-or-hdsstyles-not-recommended.

----

The <HEAD> becomes quite small now, which is good for the ISR generated pages, since there isn't (style) code blocks that would be duplicated.

```
  <head>
    <meta charSet="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <meta name="next-head-count" content="2" />
    <link
      rel="preload"
      href="/_next/static/css/0dbe50436420d99c.css"
      as="style"
    />
    <link
      rel="stylesheet"
      href="/_next/static/css/0dbe50436420d99c.css"
      data-n-g=""
    />
    <noscript data-n-css=""></noscript>
    <script
      defer=""
      nomodule=""
      src="/_next/static/chunks/polyfills-78c92fac7aa8fdd8.js"
    ></script>
    <script
      src="/_next/static/chunks/webpack-84bacf5241291d02.js"
      defer=""
    ></script>
    <script
      src="/_next/static/chunks/framework-82e56b5bc7f38c7c.js"
      defer=""
    ></script>
    <script
      src="/_next/static/chunks/main-40386d873a9a2799.js"
      defer=""
    ></script>
    <script
      src="/_next/static/chunks/pages/_app-cac59e8557c3eb63.js"
      defer=""
    ></script>
    <script
      src="/_next/static/chunks/pages/articles-179bac17ffdbc32a.js"
      defer=""
    ></script>
    <script
      src="/_next/static/10TLyW7Gy_2eM5r8jFw7B/_buildManifest.js"
      defer=""
    ></script>
    <script
      src="/_next/static/10TLyW7Gy_2eM5r8jFw7B/_ssgManifest.js"
      defer=""
    ></script>
  </head>
```

----

### Critical HDS Styles

Some Helsinki Design System (HDS) CSS styles are critically needed and luckily the HDS exposes a tool for extracting the used critical styles of HDS components. The HDS team [recommends](https://hds.hel.fi/foundation/guidelines/server-side-rendering/#how-does-hds-support-server-side-rendering) using their `getCriticalHdsRules` tool with the `_document.tsx` file of the Next JS, but when using NextJS with Static Site Generation (SSG) and Incremental Static Regeneration (ISR), it would mean that the inline style-block would be cloned again and again in every statically generated page and it would not be cached any how by the client (browser). Because of that, we have a custom script in the monorepo root, that we can use to create a CSS file to all the monorepo apps (and also in common packages where it is needed).

By executing `yarn g:hds-critical-styles-create`, the `critical-hds-styles.css` file will be created in every app and package where needed. The command uses the yarn workspaces and the related apps' `yarn hds:critical-styles:create` -command to do that.

### CODE REVIEW

**Comment by nikomakela** [comment]
By importing the HDS styles with the `Used-styles` and importing them as an inline style block on every generated page, import all the styles as the global styles, so they are linked to the generated page created by ISR / SSG.

More about this:
1. https://hds.hel.fi/foundation/guidelines/server-side-rendering/
2. https://github.com/theKashey/used-styles.

When the used-styles option is used, there will be an inline style-block rendered inside the Document-component. That approach makes the loading of styles really fast, but it would grow the size of the generated pages. If there are hundreds or thousands of ISR generated pages, it would mean that there would be the same inline-style-block, duplicated as many times as well and the browser couldn't take an advantage from caching the styles.

However, if the full HDS stylesheet was imported, many component styles broke because we could not rely on the styles that becomes the active ones. When the linked styles for HDS are used, there are some issues with the CSS priorisation: Some buttons that used to be black are now blue and some flex-forms now aligns the buttons on wrong side, etc. I think all this is to due to the fact that when there are multiple global CSS files imported, the NextJS utils and tools splits the code in multipel CSS stylesheet files and after that the styles are prioritized the same.

There can also be some kind of bug still in the NextJS code, because there are discussions about this kind of matter:

[CSS Modules styles defined in wrong order in development mode · Issue #13092 · vercel/next.js](https://github.com/vercel/next.js/issues/13092)

[Verify CSS import ordering · Issue #16630 · vercel/next.js](https://github.com/vercel/next.js/issues/16630)  

[Inconsistent loading order of CSS Modules + global CSS · Issue #10148 · vercel/next.js](https://github.com/vercel/next.js/issues/10148)

**Comment by terovirtanen** [comment]
**VENUE GRAPHQL PROXY is deployed to platta: https://venue-graphql-proxy-pr615.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Hobbies-Helsinki branch is deployed to platta: https://harrastukset-pr615.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Sports-Helsinki branch is deployed to platta: https://liikunta-pr615.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Events-Helsinki branch is deployed to platta: https://tapahtumat-pr615.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**EVENTS GRAPHQL PROXY is deployed to platta: https://events-graphql-proxy-pr615.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://harrastukset-pr615.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://tapahtumat-pr615.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**Hobbies-Helsinki branch is deployed to platta: https://harrastukset-pr615.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://tapahtumat-pr615.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**EVENTS GRAPHQL PROXY is deployed to platta: https://events-graphql-proxy-pr615.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**VENUE GRAPHQL PROXY is deployed to platta: https://venue-graphql-proxy-pr615.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Sports-Helsinki branch is deployed to platta: https://liikunta-pr615.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://liikunta-pr615.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**Events-Helsinki branch is deployed to platta: https://tapahtumat-pr615.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Hobbies-Helsinki branch is deployed to platta: https://harrastukset-pr615.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://tapahtumat-pr615.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://harrastukset-pr615.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**VENUE GRAPHQL PROXY is deployed to platta: https://venue-graphql-proxy-pr615.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**EVENTS GRAPHQL PROXY is deployed to platta: https://events-graphql-proxy-pr615.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Sports-Helsinki branch is deployed to platta: https://liikunta-pr615.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://liikunta-pr615.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**Hobbies-Helsinki branch is deployed to platta: https://harrastukset-pr615.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Events-Helsinki branch is deployed to platta: https://tapahtumat-pr615.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**VENUE GRAPHQL PROXY is deployed to platta: https://venue-graphql-proxy-pr615.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**EVENTS GRAPHQL PROXY is deployed to platta: https://events-graphql-proxy-pr615.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://tapahtumat-pr615.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://harrastukset-pr615.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**Sports-Helsinki branch is deployed to platta: https://liikunta-pr615.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://liikunta-pr615.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**Events-Helsinki branch is deployed to platta: https://tapahtumat-pr615.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://tapahtumat-pr615.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**EVENTS GRAPHQL PROXY is deployed to platta: https://events-graphql-proxy-pr615.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://harrastukset-pr615.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**VENUE GRAPHQL PROXY is deployed to platta: https://venue-graphql-proxy-pr615.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Sports-Helsinki branch is deployed to platta: https://liikunta-pr615.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://liikunta-pr615.dev.hel.ninja :laughing::tada::tada::tada:

**Review by karisal-anders — APPROVED** [review]
Looks maintainable now to me! 👍

Thoughts for future PRs:
- Refactoring the styles from all the apps and moving them to packages/components would be good for reducing code triplication.

**Comment by terovirtanen** [comment]
**Events-Helsinki branch is deployed to platta: https://tapahtumat-pr615.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Hobbies-Helsinki branch is deployed to platta: https://harrastukset-pr615.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://tapahtumat-pr615.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://harrastukset-pr615.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**EVENTS GRAPHQL PROXY is deployed to platta: https://events-graphql-proxy-pr615.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**VENUE GRAPHQL PROXY is deployed to platta: https://venue-graphql-proxy-pr615.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://liikunta-pr615.dev.hel.ninja :laughing::tada::tada::tada:

**Pull request merged**
