### PR TITLE
fix: upgrade to HDS v3.7 & RHHC v1.0.0-alpha272, remove menu workaround

### PR DESCRIPTION
**Pull request by karisal-anders**
### fix: upgrade to HDS v3.7 & RHHC v1.0.0-alpha272, remove menu workaround

remove workaround made in 3644ce4e2681736e574b42e223bbe5917a398270
for LIIKUNTA-627 as HDS v3.7 it is not needed anymore

refs LIIKUNTA-627

### Related

[LIIKUNTA-627](https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-627)

## Screenshots

image

## Additional notes

[LIIKUNTA-627]: https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-627?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by terovirtanen** [comment]
**Sports-Helsinki branch is deployed to platta: https://liikunta-pr668.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Hobbies-Helsinki branch is deployed to platta: https://harrastukset-pr668.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://liikunta-pr668.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**Events-Helsinki branch is deployed to platta: https://tapahtumat-pr668.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://harrastukset-pr668.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://tapahtumat-pr668.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**EVENTS GRAPHQL PROXY is deployed to platta: https://events-graphql-proxy-pr668.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**VENUE GRAPHQL PROXY is deployed to platta: https://venue-graphql-proxy-pr668.dev.hel.ninja** :rocket::rocket::rocket:

**Review by melniiv — APPROVED** [review]

**Pull request merged**
