### PR TITLE
chore: rename events-graphql-proxy Image to EventImage, update supergraph

### PR DESCRIPTION
**Pull request by karisal-anders**
### chore: rename events-graphql-proxy Image to EventImage, update supergraph

NOTE:
 - THIS **NEEDS HCRC** (i.e. react-helsinki-headless-cms) related changes (See **[PR #114](https://github.com/City-of-Helsinki/react-helsinki-headless-cms/pull/114)**) in tandem for things **to work**, the Image type needs to be updated there also to EventImage i.e. EventsByIdsQuery -> eventsByIds -> data -> images -> __typename should be changed from 'Image' to 'EventImage'.

what was done:

events-graphql-proxy:
 - renamed Image to EventImage
 - renamed ImageResolvers to EventImageResolvers

```bash
cd ./proxies/events-graphql-proxy
yarn build
yarn start
```
-> events-graphql-proxy running at http://localhost:4100/proxy/graphql

Changed temporarily `docker:graphql-router:sports:serve` command in package.json to make the router use the local events-graphql-proxy by setting FEDERATION_EVENTS_ROUTING_URL to
http://host.docker.internal:4100/proxy/graphql

See https://stackoverflow.com/a/24326540 for information about the use of host.docker.internal instead of localhost.

Ran the events-graphql-federation router and made sure it builds: `yarn docker:graphql-router:sports:serve --build`
-> events-graphql-federation running at http://localhost:4000/

```bash
cd ./proxies/events-graphql-federation
rover subgraph introspect http://localhost:4100/proxy/graphql \
    > ./subgraphs/events/events.graphql
rover graph introspect https://harrastus.hkih.stage.geniem.io/graphql \
    > ./subgraphs/cms/cms.graphql
rover supergraph compose --config ./supergraph-config.yaml \
    > ./supergraph.graphql
```
which resulted in an error:
```bash
error[E029]: Encountered 1 build error while trying to build a
supergraph.

Caused by:
    INVALID_GRAPHQL: [cms] - Syntax Error:
    Invalid character escape sequence: "\s".

    GraphQL request:7347:23
    7346 |   NICENAME
    7347 |   "The URL of the user\s website."
         |                       ^
    7348 |   URL
```

Manually renamed in generated cms.graphql:
 - `"The URL of the user\s website."` to
 - `"The URL of the user's website."`

and ran the rover supergraph compose command again which succeeded in generating the supergraph.

Stopped the locally running router and rebuilt it to make sure the supergraph changes got reflected in it:
`yarn docker:graphql-router:sports:serve --build`

Set `FEDERATION_ROUTER_ENDPOINT="http://localhost:4000/"` in apps/sports-helsinki/.env.local so "yarn generate:graphql" will use the locally running router.

Generated the graphql:
```bash
cd ../../apps/sports-helsinki/
yarn generate:graphql
cp ./src/components/domain/graphql/generated/graphql.tsx \
    ../../packages/components/src/types/generated/
cd ../../
npx prettier ./packages/components/src/types/generated/graphql.tsx -w
```

Renamed Image to EventImage in mocking and fakeImage to fakeEventImage.

### CODE REVIEW

**Review by melniiv — APPROVED** [review]

**Comment by terovirtanen** [comment]
**Federation Router branch is deployed to platta: https://events-graphql-federation-sports-pr413.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Federation Router branch is deployed to platta: https://events-graphql-federation-hobbies-pr413.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Federation Router branch is deployed to platta: https://events-graphql-federation-events-pr413.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**EVENTS GRAPHQL PROXY is deployed to platta: https://events-graphql-proxy-pr413.dev.hel.ninja** :rocket::rocket::rocket:

**Pull request merged**
