### PR TITLE
feat(sports): switch landing search shortcuts to Liikunta ones

### PR DESCRIPTION
**Pull request by tuomas777**
Added proper Liikunta/Sports search shortcuts to the landing page. A couple of them are still missing an icon, so the "sports" icon is used for those (a bicycle).

The shortcuts will direct the user to the advanced search with the selected shortcut as a category in the URL, but there is currently no actual search performed based on that. Also, the automated seasonal shortcut switching feature from the old Liikunta/Sports has not been implemented yet.

## Issues

**[LIIKUNTA-334](https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-334)**

## Screenshots
Screenshot 2022-12-13 at 9 26 47
Screenshot 2022-12-13 at 9 16 41

### CODE REVIEW

**Comment by terovirtanen** [comment]
**Hobbies-Helsinki branch is deployed to platta: https://harrastukset-107-liikunta-334-update-search-links-in-front-page.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Events-Helsinki branch is deployed to platta: https://tapahtumat-107-liikunta-334-update-search-links-in-front-page.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Sports-Helsinki branch is deployed to platta: https://liikunta-107-liikunta-334-update-search-links-in-front-page.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Hobbies-Helsinki branch is deployed to platta: https://harrastukset-107-liikunta-334-update-search-links-in-front-page.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Events-Helsinki branch is deployed to platta: https://tapahtumat-107-liikunta-334-update-search-links-in-front-page.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Sports-Helsinki branch is deployed to platta: https://liikunta-107-liikunta-334-update-search-links-in-front-page.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Events-Helsinki branch is deployed to platta: https://tapahtumat-107-liikunta-334-update-search-links-in-front-page.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Hobbies-Helsinki branch is deployed to platta: https://harrastukset-107-liikunta-334-update-search-links-in-front-page.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Events-Helsinki branch is deployed to platta: https://tapahtumat-107-liikunta-334-update-search-links-in-front-page.dev.hel.ninja** :rocket::rocket::rocket:

**Review by nikomakela — APPROVED** [review]

**Comment by nikomakela** [comment]
BTW, why did the hobbies and events CI get triggered when the changes are only for sports?

**Comment by terovirtanen** [comment]
**Hobbies-Helsinki branch is deployed to platta: https://harrastukset-107-liikunta-334-update-search-links-in-front-page.dev.hel.ninja** :rocket::rocket::rocket:

**Pull request merged**
