### PR TITLE
LIIKUNTA-344 | feat(sports): update events/hobby search related target group keywords

### PR DESCRIPTION
**Pull request by karisal-anders**
### feat(sports): update events/hobby search related target group keywords

refs LIIKUNTA-344

### Related

**[LIIKUNTA-344](https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-344)**

## Additional notes

[LIIKUNTA-344]: https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-344?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by terovirtanen** [comment]
**Sports-Helsinki branch is deployed to platta: https://liikunta-pr511.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://liikunta-pr511.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by karisal-anders** [comment]
TODO:
 - [ ] Fix tests

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://liikunta-pr511.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by karisal-anders** [comment]
Fixed the tests, ready for review.

**Review by nikomakela — APPROVED** [review]

**Pull request merged**
