### PR TITLE
LIIKUNTA-555 | test(cookies): add test for AppConfig.hostname so cookieDomain will work

### PR DESCRIPTION
**Pull request by karisal-anders**
### test(cookies): add test for AppConfig.hostname so cookieDomain will work

refs LIIKUNTA-555 (started to use cookieDomain)

### Closes

[LIIKUNTA-555](https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-555)

## Additional notes

[LIIKUNTA-555]: https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-555?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by terovirtanen** [comment]
**Events-Helsinki branch is deployed to platta: https://tapahtumat-pr524.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Sports-Helsinki branch is deployed to platta: https://liikunta-pr524.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://tapahtumat-pr524.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by karisal-anders** [comment]
TODO:
 - [ ] Fix tests

```
Summary of all failing tests
FAIL domain/app/__tests__/Hostname.test.tsx
  ● AppConfig.hostname corresponds to window.location.hostname

    expect(received).toStrictEqual(expected) // deep equality

    Expected: "localhost"
    Received: "liikunta-pr524.dev.hel.ninja"

      4 |   // If this test fails the cookieDomain setting won't work with CookieModal/CookiePage
      5 |   // and trying to close the cookie consent modal/page will fail
    > 6 |   expect(AppConfig.hostname).toStrictEqual(window.location.hostname);
        |                              ^
      7 | });
      8 |

      at Object.toStrictEqual (domain/app/__tests__/Hostname.test.tsx:6:30)
```

**Comment by terovirtanen** [comment]
**Hobbies-Helsinki branch is deployed to platta: https://harrastukset-pr524.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Events-Helsinki branch is deployed to platta: https://tapahtumat-pr524.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://harrastukset-pr524.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**Sports-Helsinki branch is deployed to platta: https://liikunta-pr524.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://liikunta-pr524.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**Events-Helsinki branch is deployed to platta: https://tapahtumat-pr524.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Hobbies-Helsinki branch is deployed to platta: https://harrastukset-pr524.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://harrastukset-pr524.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**Sports-Helsinki branch is deployed to platta: https://liikunta-pr524.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://liikunta-pr524.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by karisal-anders** [comment]
Seems this is trickier than I initially thought. Closing to remove clutter from the open PR list.

**Pull request closed without merging**
