### PR TITLE
HCRC-114 | feat: update to HDS 3.9

### PR DESCRIPTION
**Pull request by melniiv**
## Description
1. update HDS to 3.9 version
2. Add hamburger menu translations
3. HCRC: fix single image module to hide action buttons and implement hamburger menu translations
image

### Closes

**[DEV-XXX](https://helsinkisolutionoffice.atlassian.net/browse/DEV-XXX):**

### CODE REVIEW

**Comment by terovirtanen** [comment]
**Events-Helsinki branch is deployed to platta: https://tapahtumat-pr717.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Hobbies-Helsinki branch is deployed to platta: https://harrastukset-pr717.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Sports-Helsinki branch is deployed to platta: https://liikunta-pr717.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://tapahtumat-pr717.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://liikunta-pr717.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://harrastukset-pr717.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**VENUE GRAPHQL PROXY is deployed to platta: https://venue-graphql-proxy-pr717.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**EVENTS GRAPHQL PROXY is deployed to platta: https://events-graphql-proxy-pr717.dev.hel.ninja** :rocket::rocket::rocket:

**Review by karisal-anders — APPROVED** [review]
Otherwise looks ok, but I'm a bit on guard so to speak with having now multiple versions of apollo client installed [1]... so that might bring trouble later on. Might be good to look into the possible deduplication of apollo-client versions in RHHC and in events-helsinki-monorepo:

[1] From `yarn.lock`:
```
"@apollo/client@npm:3.7.16":
  version: 3.7.16
  resolution: "@apollo/client@npm:3.7.16"
...
"@apollo/client@npm:^3.10.1":
  version: 3.10.8
  resolution: "@apollo/client@npm:3.10.8"
```

**Pull request merged**
