### PR TITLE
feat: use CMS provided carousel show all URLs

### PR DESCRIPTION
**Pull request by tuomas777**
### Closes

**[HCRC-78](https://helsinkisolutionoffice.atlassian.net/browse/HCRC-78): As a content manager I can add a show all -link in the carousel**

### CODE REVIEW

**Comment by terovirtanen** [comment]
**Sports-Helsinki branch is deployed to platta: https://liikunta-101-use-cms-provided-carousel-show-all-urls.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Hobbies-Helsinki branch is deployed to platta: https://harrastukset-101-use-cms-provided-carousel-show-all-urls.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Events-Helsinki branch is deployed to platta: https://tapahtumat-101-use-cms-provided-carousel-show-all-urls.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Sports-Helsinki branch is deployed to platta: https://liikunta-101-use-cms-provided-carousel-show-all-urls.dev.hel.ninja** :rocket::rocket::rocket:

**Review by nikomakela — APPROVED** [review]

**Comment by terovirtanen** [comment]
**Hobbies-Helsinki branch is deployed to platta: https://harrastukset-101-use-cms-provided-carousel-show-all-urls.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Events-Helsinki branch is deployed to platta: https://tapahtumat-101-use-cms-provided-carousel-show-all-urls.dev.hel.ninja** :rocket::rocket::rocket:

**Pull request merged**
