### PR TITLE
feat(hobbies): remove search link and categories from footer

### PR DESCRIPTION
**Pull request by tuomas777**
### Closes

**[HH-267](https://helsinkisolutionoffice.atlassian.net/browse/HH-267)**

## Screenshots
Screenshot 2022-12-14 at 16 55 53

### CODE REVIEW

**Comment by terovirtanen** [comment]
**Events-Helsinki branch is deployed to platta: https://tapahtumat-pr113.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Sports-Helsinki branch is deployed to platta: https://liikunta-pr113.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Sports-Helsinki branch is deployed to platta: https://liikunta-pr113.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Sports-Helsinki branch is deployed to platta: https://liikunta-pr113.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Hobbies-Helsinki branch is deployed to platta: https://harrastukset-pr113.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Events-Helsinki branch is deployed to platta: https://tapahtumat-pr113.dev.hel.ninja** :rocket::rocket::rocket:

**Review by melniiv — APPROVED** [review]
lgtm

**Pull request merged**
