### PR TITLE
LIIKUNTA-511 | chore: update generated GraphQL types after PR #403 router schema change

### PR DESCRIPTION
**Pull request by karisal-anders**
### chore: update generated GraphQL types after PR #403 router schema change

what was done:
```bash
cd apps/sports-helsinki/
yarn generate:graphql
cp ./src/components/domain/graphql/generated/graphql.tsx \
    ../../packages/components/src/types/generated/
cd ../../
npx prettier ./packages/components/src/types/generated/graphql.tsx -w
```

Made sure that FEDERATION_ROUTER_ENDPOINT was set to
https://events-graphql-federation-sports.test.hel.ninja/

refs LIIKUNTA-511 (testing unified search changes)

## Issues

**[LIIKUNTA-511](https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-511)**

## Additional notes

The diff without the extra changes:
 - removed `\['(output|input)'\]`
 - replaced `\{ input: (\w+); output: \1 \}` with `$1`
 - replaced `\<\n(\s+)\|\s*` with `<`
 - ran npx prettier on both graphql.tsx files to be diffed
 - fixed remaining whitespace changes manually

Result:

```diff
@@ -1,59 +1,107 @@
 import { gql } from '@apollo/client';
 import * as Apollo from '@apollo/client';
 export type Maybe<T> = T | null;
 export type InputMaybe<T> = Maybe<T>;
 export type Exact<T extends { [key: string]: unknown }> = {
   [K in keyof T]: T[K];
 };
 export type MakeOptional<T, K extends keyof T> = Omit<T, K> & {
   [SubKey in K]?: Maybe<T[SubKey]>;
 };
 export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & {
   [SubKey in K]: Maybe<T[SubKey]>;
 };
+export type MakeEmpty<
+  T extends { [key: string]: unknown },
+  K extends keyof T
+> = { [_ in K]?: never };
+export type Incremental<T> =
+  | T
+  | {
+      [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never;
+    };
 const defaultOptions = {} as const;
 /** All built-in and custom scalars, mapped to their actual values */
 export type Scalars = {
   ID: string;
   String: string;
   Boolean: boolean;
   Int: number;
   Float: number;
   DateTime: any;
   GeoJSONCoordinates: any;
   JSONObject: any;
 };
 
-/** TODO: take this from service map / TPREK */
-export type AccessibilityProfile = {
-  __typename?: 'AccessibilityProfile';
-  meta?: Maybe<NodeMeta>;
-  todo?: Maybe<Scalars['String']>;
+export type Accessibility = {
+  __typename?: 'Accessibility';
+  email?: Maybe<Scalars['String']>;
+  phone?: Maybe<Scalars['String']>;
+  sentences?: Maybe<Array<Maybe<AccessibilitySentence>>>;
+  shortcomings?: Maybe<Array<Maybe<AccessibilityShortcoming>>>;
+  viewpoints?: Maybe<Array<Maybe<AccessibilityViewpoint>>>;
+  www?: Maybe<Scalars['String']>;
+};
+
+export enum AccessibilityProfile {
+  HearingAid = 'hearing_aid',
+  ReducedMobility = 'reduced_mobility',
+  Rollator = 'rollator',
+  Stroller = 'stroller',
+  VisuallyImpaired = 'visually_impaired',
+  Wheelchair = 'wheelchair',
+}
+
+export type AccessibilitySentence = {
+  __typename?: 'AccessibilitySentence';
+  sentence?: Maybe<LanguageString>;
+  sentenceGroup?: Maybe<LanguageString>;
+  sentenceGroupName?: Maybe<Scalars['String']>;
 };
 
 export type AccessibilitySentences = {
   __typename?: 'AccessibilitySentences';
   groupName?: Maybe<Scalars['String']>;
   sentences?: Maybe<Array<Maybe<Scalars['String']>>>;
 };
 
+export type AccessibilityShortcoming = {
+  __typename?: 'AccessibilityShortcoming';
+  count?: Maybe<Scalars['Int']>;
+  profile?: Maybe<AccessibilityProfile>;
+};
+
+export type AccessibilityViewpoint = {
+  __typename?: 'AccessibilityViewpoint';
+  id?: Maybe<Scalars['ID']>;
+  name?: Maybe<LanguageString>;
+  shortages?: Maybe<Array<Maybe<LanguageString>>>;
+  value?: Maybe<AccessibilityViewpointValue>;
+};
+
+export enum AccessibilityViewpointValue {
+  Green = 'green',
+  Red = 'red',
+  Unknown = 'unknown',
+}
+
 /** TODO: give real structure */
 export type Address = {
   __typename?: 'Address';
   city?: Maybe<LanguageString>;
   postalCode?: Maybe<Scalars['String']>;
   streetAddress?: Maybe<LanguageString>;
 };
 
 export type AdministrativeDivision = {
   __typename?: 'AdministrativeDivision';
   id?: Maybe<Scalars['ID']>;
   municipality?: Maybe<Scalars['String']>;
   name?: Maybe<LanguageString>;
   type?: Maybe<Scalars['String']>;
 };
 
 export type Audience = {
   __typename?: 'Audience';
   id?: Maybe<Scalars['ID']>;
   internalContext?: Maybe<Scalars['String']>;
@@ -7258,40 +7306,54 @@
   /** Label for the media frame filter. */
   uploadedToThisItem?: Maybe<Scalars['String']>;
   /** Label in the media frame for using a featured image. */
   useFeaturedImage?: Maybe<Scalars['String']>;
   /** Label for viewing a singular item. */
   viewItem?: Maybe<Scalars['String']>;
   /** Label for viewing post type archives. */
   viewItems?: Maybe<Scalars['String']>;
 };
 
 /** Nodes that can be seen in a preview (unpublished) state. */
 export type Previewable = {
   /** Whether the object is a node in the preview state */
   isPreview?: Maybe<Scalars['Boolean']>;
   /** The database id of the preview node */
   previewRevisionDatabaseId?: Maybe<Scalars['Int']>;
   /** Whether the object is a node in the preview state */
   previewRevisionId?: Maybe<Scalars['ID']>;
 };
 
+export enum ProviderType {
+  Association = 'ASSOCIATION',
+  ContractSchool = 'CONTRACT_SCHOOL',
+  Municipality = 'MUNICIPALITY',
+  OtherProductionMethod = 'OTHER_PRODUCTION_METHOD',
+  PaymentCommitment = 'PAYMENT_COMMITMENT',
+  PrivateCompany = 'PRIVATE_COMPANY',
+  PurchasedService = 'PURCHASED_SERVICE',
+  SelfProduced = 'SELF_PRODUCED',
+  SupportedOperations = 'SUPPORTED_OPERATIONS',
+  UnknownProductionMethod = 'UNKNOWN_PRODUCTION_METHOD',
+  VoucherService = 'VOUCHER_SERVICE',
+}
+
 /** The root entry point into the Graph */
 export type Query = {
   __typename?: 'Query';
   _empty?: Maybe<Scalars['String']>;
   administrativeDivisions?: Maybe<Array<Maybe<AdministrativeDivision>>>;
   /** Entry point to get all settings for the site */
   allSettings?: Maybe<Settings>;
   /** Connection between the RootQuery type and the category type */
   categories?: Maybe<RootQueryToCategoryConnection>;
   /** A 0bject */
   category?: Maybe<Category>;
   /** An object of the collection Type. Collections */
   collection?: Maybe<Collection>;
   /**
    * A collection object
    * @deprecated Deprecated in favor of using the single entry point for this type with ID and IDType fields. For example, instead of postBy( id: &quot;&quot; ), use post(id: &quot;&quot; idType: &quot;&quot;)
    */
   collectionBy?: Maybe<Collection>;
   /** Connection between the RootQuery type and the collection type */
   collections?: Maybe<RootQueryToCollectionConnection>;
@@ -7999,56 +8061,61 @@
 
 /** The root entry point into the Graph */
 export type QueryTranslationByArgs = {
   id?: InputMaybe<Scalars['ID']>;
   slug?: InputMaybe<Scalars['String']>;
   translationId?: InputMaybe<Scalars['Int']>;
   uri?: InputMaybe<Scalars['String']>;
 };
 
 /** The root entry point into the Graph */
 export type QueryTranslationsArgs = {
   after?: InputMaybe<Scalars['String']>;
   before?: InputMaybe<Scalars['String']>;
   first?: InputMaybe<Scalars['Int']>;
   last?: InputMaybe<Scalars['Int']>;
   where?: InputMaybe<RootQueryToTranslationConnectionWhereArgs>;
 };
 
 /** The root entry point into the Graph */
 export type QueryUnifiedSearchArgs = {
+  accessibilityProfilesWithoutShortcomings?: InputMaybe<Array<InputMaybe<AccessibilityProfile>>>;
   administrativeDivisionId?: InputMaybe<Scalars['ID']>;
   administrativeDivisionIds?: InputMaybe<Array<InputMaybe<Scalars['ID']>>>;
   after?: InputMaybe<Scalars['String']>;
   before?: InputMaybe<Scalars['String']>;
   first?: InputMaybe<Scalars['Int']>;
   index?: InputMaybe<Scalars['String']>;
   languages?: Array<UnifiedSearchLanguage>;
   last?: InputMaybe<Scalars['Int']>;
+  mustHaveReservableResource?: InputMaybe<Scalars['Boolean']>;
   ontology?: InputMaybe<Scalars['String']>;
   ontologyTreeId?: InputMaybe<Scalars['ID']>;
   ontologyTreeIds?: InputMaybe<Array<InputMaybe<Scalars['ID']>>>;
   ontologyWordIds?: InputMaybe<Array<InputMaybe<Scalars['ID']>>>;
   openAt?: InputMaybe<Scalars['String']>;
   orderByDistance?: InputMaybe<OrderByDistance>;
   orderByName?: InputMaybe<OrderByName>;
+  providerTypes?: InputMaybe<Array<InputMaybe<ProviderType>>>;
   q?: InputMaybe<Scalars['String']>;
+  serviceOwnerTypes?: InputMaybe<Array<InputMaybe<ServiceOwnerType>>>;
+  targetGroups?: InputMaybe<Array<InputMaybe<TargetGroup>>>;
 };
 
 /** The root entry point into the Graph */
 export type QueryUnifiedSearchCompletionSuggestionsArgs = {
   index?: InputMaybe<Scalars['String']>;
   languages?: Array<UnifiedSearchLanguage>;
   prefix?: InputMaybe<Scalars['String']>;
   size?: InputMaybe<Scalars['Int']>;
 };
 
 /** The root entry point into the Graph */
 export type QueryUserArgs = {
   id: Scalars['ID'];
   idType?: InputMaybe<UserNodeIdTypeEnum>;
 };
 
 /** The root entry point into the Graph */
 export type QueryUserRoleArgs = {
   id: Scalars['ID'];
 };
@@ -8388,54 +8455,88 @@
 export type ResetUserPasswordInput = {
   /** This is an ID that can be passed to a mutation by the client to track the progress of mutations and catch possible duplicate mutation submissions. */
   clientMutationId?: InputMaybe<Scalars['String']>;
   /** Password reset key */
   key?: InputMaybe<Scalars['String']>;
   /** The user's login (username). */
   login?: InputMaybe<Scalars['String']>;
   /** The new password. */
   password?: InputMaybe<Scalars['String']>;
 };
 
 /** The payload for the resetUserPassword mutation. */
 export type ResetUserPasswordPayload = {
   __typename?: 'ResetUserPasswordPayload';
   /** If a &#039;clientMutationId&#039; input is provided to the mutation, it will be returned as output on the mutation. This ID can be used by the client to track the progress of mutations and catch possible duplicate mutation submissions. */
   clientMutationId?: Maybe<Scalars['String']>;
   /** The User object mutation type. */
   user?: Maybe<User>;
 };
 
+export type Resource = {
+  __typename?: 'Resource';
+  description?: Maybe<LanguageString>;
+  externalReservationUrl?: Maybe<Scalars['String']>;
+  genericTerms?: Maybe<LanguageString>;
+  id?: Maybe<Scalars['ID']>;
+  name?: Maybe<LanguageString>;
+  paymentTerms?: Maybe<LanguageString>;
+  reservable?: Maybe<Scalars['Boolean']>;
+  reservationInfo?: Maybe<LanguageString>;
+  responsibleContactInfo?: Maybe<LanguageString>;
+  specificTerms?: Maybe<LanguageString>;
+  type?: Maybe<ResourceType>;
+  userPermissions?: Maybe<ResourceUserPermissions>;
+};
+
+export enum ResourceMainType {
+  Item = 'item',
+  Person = 'person',
+  Space = 'space',
+}
+
 export enum ResourceState {
   Closed = 'closed',
   EnterOnly = 'enter_only',
   ExitOnly = 'exit_only',
   Open = 'open',
   OpenAndReservable = 'open_and_reservable',
   SelfService = 'self_service',
   Undefined = 'undefined',
   WeatherPermitting = 'weather_permitting',
   WithKey = 'with_key',
   WithKeyAndReservation = 'with_key_and_reservation',
   WithReservation = 'with_reservation',
 }
 
+export type ResourceType = {
+  __typename?: 'ResourceType';
+  id?: Maybe<Scalars['ID']>;
+  mainType?: Maybe<ResourceMainType>;
+  name?: Maybe<LanguageString>;
+};
+
+export type ResourceUserPermissions = {
+  __typename?: 'ResourceUserPermissions';
+  canMakeReservations?: Maybe<Scalars['Boolean']>;
+};
+
 /** Input for the restoreComment mutation. */
 export type RestoreCommentInput = {
   /** This is an ID that can be passed to a mutation by the client to track the progress of mutations and catch possible duplicate mutation submissions. */
   clientMutationId?: InputMaybe<Scalars['String']>;
   /** The ID of the comment to be restored */
   id: Scalars['ID'];
 };
 
 /** The payload for the restoreComment mutation. */
 export type RestoreCommentPayload = {
   __typename?: 'RestoreCommentPayload';
   /** If a &#039;clientMutationId&#039; input is provided to the mutation, it will be returned as output on the mutation. This ID can be used by the client to track the progress of mutations and catch possible duplicate mutation submissions. */
   clientMutationId?: Maybe<Scalars['String']>;
   /** The restored comment object */
   comment?: Maybe<Comment>;
   /** The ID of the restored comment */
   restoredId?: Maybe<Scalars['ID']>;
 };
 
 /** Connection between the RootQuery type and the category type */
@@ -9857,40 +9958,65 @@
 /** The payload for the sendPasswordResetEmail mutation. */
 export type SendPasswordResetEmailPayload = {
   __typename?: 'SendPasswordResetEmailPayload';
   /** If a &#039;clientMutationId&#039; input is provided to the mutation, it will be returned as output on the mutation. This ID can be used by the client to track the progress of mutations and catch possible duplicate mutation submissions. */
   clientMutationId?: Maybe<Scalars['String']>;
   /** Whether the mutation completed successfully. This does NOT necessarily mean that an email was sent. */
   success?: Maybe<Scalars['Boolean']>;
   /**
    * The user that the password reset email was sent to
    * @deprecated This field will be removed in a future version of WPGraphQL
    */
   user?: Maybe<User>;
 };
 
 export type SeoSettings = {
   __typename?: 'SeoSettings';
   /** Title separator setting for seo titles */
   separator?: Maybe<Scalars['String']>;
 };
 
+export type ServiceOwner = {
+  __typename?: 'ServiceOwner';
+  name?: Maybe<LanguageString>;
+  providerType?: Maybe<ProviderType>;
+  type?: Maybe<ServiceOwnerType>;
+};
+
+export enum ServiceOwnerType {
+  MunicipalService = 'MUNICIPAL_SERVICE',
+  NotDisplayed = 'NOT_DISPLAYED',
+  PrivateContractSchool = 'PRIVATE_CONTRACT_SCHOOL',
+  PrivateService = 'PRIVATE_SERVICE',
+  PurchasedService = 'PURCHASED_SERVICE',
+  ServiceByJointMunicipalAuthority = 'SERVICE_BY_JOINT_MUNICIPAL_AUTHORITY',
+  ServiceByMunicipallyOwnedCompany = 'SERVICE_BY_MUNICIPALLY_OWNED_COMPANY',
+  ServiceByMunicipalGroupEntity = 'SERVICE_BY_MUNICIPAL_GROUP_ENTITY',
+  ServiceByOtherMunicipality = 'SERVICE_BY_OTHER_MUNICIPALITY',
+  ServiceByRegionalCooperationOrganization = 'SERVICE_BY_REGIONAL_COOPERATION_ORGANIZATION',
+  ServiceByWellbeingArea = 'SERVICE_BY_WELLBEING_AREA',
+  StateContractSchool = 'STATE_CONTRACT_SCHOOL',
+  StateService = 'STATE_SERVICE',
+  SupportedOperations = 'SUPPORTED_OPERATIONS',
+  VoucherService = 'VOUCHER_SERVICE',
+}
+
 /** All of the registered settings */
 export type Settings = {
   __typename?: 'Settings';
   /** Settings of the the string Settings Group */
   discussionSettingsDefaultCommentStatus?: Maybe<Scalars['String']>;
   /** Settings of the the string Settings Group */
   discussionSettingsDefaultPingStatus?: Maybe<Scalars['String']>;
   /** Settings of the the string Settings Group */
   generalSettingsDateFormat?: Maybe<Scalars['String']>;
   /** Settings of the the string Settings Group */
   generalSettingsDescription?: Maybe<Scalars['String']>;
   /** Settings of the the string Settings Group */
   generalSettingsLanguage?: Maybe<Scalars['String']>;
   /** Settings of the the integer Settings Group */
   generalSettingsStartOfWeek?: Maybe<Scalars['Int']>;
   /** Settings of the the string Settings Group */
   generalSettingsTimeFormat?: Maybe<Scalars['String']>;
   /** Settings of the the string Settings Group */
   generalSettingsTimezone?: Maybe<Scalars['String']>;
   /** Settings of the the string Settings Group */
@@ -10254,40 +10380,51 @@
   tagNotIn?: InputMaybe<Array<InputMaybe<Scalars['ID']>>>;
   /** Array of tag slugs, used to display objects from one tag AND another */
   tagSlugAnd?: InputMaybe<Array<InputMaybe<Scalars['String']>>>;
   /** Array of tag slugs, used to include objects in ANY specified tags */
   tagSlugIn?: InputMaybe<Array<InputMaybe<Scalars['String']>>>;
   /** Title of the object */
   title?: InputMaybe<Scalars['String']>;
 };
 
 /** Connection between the Tag type and the Taxonomy type */
 export type TagToTaxonomyConnectionEdge = Edge &
   OneToOneConnection &
   TaxonomyConnectionEdge & {
     __typename?: 'TagToTaxonomyConnectionEdge';
     /** Opaque reference to the nodes position in the connection. Value can be used with pagination args. */
     cursor?: Maybe<Scalars['String']>;
     /** The node of the connection, without the edges */
     node: Taxonomy;
   };
 
+export enum TargetGroup {
+  Associations = 'ASSOCIATIONS',
+  ChildrenAndFamilies = 'CHILDREN_AND_FAMILIES',
+  Disabled = 'DISABLED',
+  ElderlyPeople = 'ELDERLY_PEOPLE',
+  Enterprises = 'ENTERPRISES',
+  Immigrants = 'IMMIGRANTS',
+  Individuals = 'INDIVIDUALS',
+  Youth = 'YOUTH',
+}
+
 /** A taxonomy object */
 export type Taxonomy = Node & {
   __typename?: 'Taxonomy';
   /** List of Content Types associated with the Taxonomy */
   connectedContentTypes?: Maybe<TaxonomyToContentTypeConnection>;
   /** Description of the taxonomy. This field is equivalent to WP_Taxonomy-&gt;description */
   description?: Maybe<Scalars['String']>;
   /** The plural name of the post type within the GraphQL Schema. */
   graphqlPluralName?: Maybe<Scalars['String']>;
   /** The singular name of the post type within the GraphQL Schema. */
   graphqlSingleName?: Maybe<Scalars['String']>;
   /** Whether the taxonomy is hierarchical */
   hierarchical?: Maybe<Scalars['Boolean']>;
   /** The globally unique identifier of the taxonomy object. */
   id: Scalars['ID'];
   /** Whether the object is restricted from the current viewer */
   isRestricted?: Maybe<Scalars['Boolean']>;
   /** Name of the taxonomy shown in the menu. Usually plural. */
   label?: Maybe<Scalars['String']>;
   /** The display name of the taxonomy. This field is equivalent to WP_Taxonomy-&gt;label */
@@ -10836,56 +10973,59 @@
   Fi = 'FI',
 }
 
 export enum UnifiedSearchResultCategory {
   Article = 'ARTICLE',
   Artwork = 'ARTWORK',
   Enrollable = 'ENROLLABLE',
   Event = 'EVENT',
   PointOfInterest = 'POINT_OF_INTEREST',
   Reservable = 'RESERVABLE',
   Service = 'SERVICE',
 }
 
 /**
  * A place that forms a unit and can be used for some specific purpose -
  * respa unit or resource, service map unit, beta.kultus venue, linked
  * events place, Kukkuu venue
  */
 export type UnifiedSearchVenue = {
   __typename?: 'UnifiedSearchVenue';
-  accessibilityProfile?: Maybe<AccessibilityProfile>;
+  accessibility?: Maybe<Accessibility>;
   additionalInfo?: Maybe<Scalars['String']>;
   arrivalInstructions?: Maybe<Scalars['String']>;
   contactDetails?: Maybe<ContactInfo>;
   description?: Maybe<LanguageString>;
   descriptionResources?: Maybe<DescriptionResources>;
   facilities?: Maybe<Array<VenueFacility>>;
   images?: Maybe<Array<Maybe<LocationImage>>>;
   location?: Maybe<LocationDescription>;
   manager?: Maybe<LegalEntity>;
   meta?: Maybe<NodeMeta>;
   name?: Maybe<LanguageString>;
   ontologyWords?: Maybe<Array<Maybe<OntologyWord>>>;
   openingHours?: Maybe<OpeningHours>;
   partOf?: Maybe<UnifiedSearchVenue>;
   reservationPolicy?: Maybe<VenueReservationPolicy>;
+  resources: Array<Resource>;
+  serviceOwner?: Maybe<ServiceOwner>;
+  targetGroups?: Maybe<Array<Maybe<TargetGroup>>>;
 };
 
 /** Any node that has a URI */
 export type UniformResourceIdentifiable = {
   /** The unique resource identifier path */
   id: Scalars['ID'];
   /** Whether the node is a Content Node */
   isContentNode: Scalars['Boolean'];
   /** Whether the node is a Term */
   isTermNode: Scalars['Boolean'];
   /** The unique resource identifier path */
   uri?: Maybe<Scalars['String']>;
 };
 
 /** Input for the updateCategory mutation. */
 export type UpdateCategoryInput = {
   /** The slug that the category will be an alias of */
   aliasOf?: InputMaybe<Scalars['String']>;
   /** This is an ID that can be passed to a mutation by the client to track the progress of mutations and catch possible duplicate mutation submissions. */
   clientMutationId?: InputMaybe<Scalars['String']>;
```

[LIIKUNTA-511]: https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-511?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by terovirtanen** [comment]
**Events-Helsinki branch is deployed to platta: https://tapahtumat-pr404.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Hobbies-Helsinki branch is deployed to platta: https://harrastukset-pr404.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://tapahtumat-pr404.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://harrastukset-pr404.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**Sports-Helsinki branch is deployed to platta: https://liikunta-pr404.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**EVENTS GRAPHQL PROXY is deployed to platta: https://events-graphql-proxy-pr404.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://liikunta-pr404.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**VENUE GRAPHQL PROXY is deployed to platta: https://venue-graphql-proxy-pr404.dev.hel.ninja** :rocket::rocket::rocket:

**Review by melniiv — APPROVED** [review]

**Pull request merged**
