### PR TITLE
feat: update venue-graphql-proxy related types and supergraph

### PR DESCRIPTION
**Pull request by karisal-anders**
## Description

This is groundwork for PR #448 

### feat: update venue-graphql-proxy related types and supergraph

refs LIIKUNTA-522 (needs this change to function)

### Related

**[LIIKUNTA-522](https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-522)**

## Additional notes

[LIIKUNTA-522]: https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-522?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by terovirtanen** [comment]
**Federation Router branch is deployed to platta: https://events-graphql-federation-events-pr469.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Federation Router branch is deployed to platta: https://events-graphql-federation-hobbies-pr469.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Federation Router branch is deployed to platta: https://events-graphql-federation-sports-pr469.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by karisal-anders** [comment]
@melniiv / @nikomakela / @jakezu Please could one of you code review this to facilitate testing of the dependent PR #448? Thank you!

**Comment by terovirtanen** [comment]
**Hobbies-Helsinki branch is deployed to platta: https://harrastukset-pr469.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://liikunta-pr469.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
## TestCafe result is __failed__ for https://tapahtumat-pr469.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by terovirtanen** [comment]
## TestCafe result is __failed__ for https://harrastukset-pr469.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by terovirtanen** [comment]
**VENUE GRAPHQL PROXY is deployed to platta: https://venue-graphql-proxy-pr469.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**EVENTS GRAPHQL PROXY is deployed to platta: https://events-graphql-proxy-pr469.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Federation Router branch is deployed to platta: https://events-graphql-federation-hobbies-pr469.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Federation Router branch is deployed to platta: https://events-graphql-federation-events-pr469.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Federation Router branch is deployed to platta: https://events-graphql-federation-sports-pr469.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Events-Helsinki branch is deployed to platta: https://tapahtumat-pr469.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Hobbies-Helsinki branch is deployed to platta: https://harrastukset-pr469.dev.hel.ninja** :rocket::rocket::rocket:

**Review by nikomakela — APPROVED** [review]

**Comment by terovirtanen** [comment]
**Sports-Helsinki branch is deployed to platta: https://liikunta-pr469.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://tapahtumat-pr469.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://harrastukset-pr469.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://liikunta-pr469.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**VENUE GRAPHQL PROXY is deployed to platta: https://venue-graphql-proxy-pr469.dev.hel.ninja** :rocket::rocket::rocket:

**Pull request merged**
