### PR TITLE
fix: replace share icons with new ones

### PR DESCRIPTION
**Pull request by melniiv**
## Description
- Fixed Twitter icon to X
- Replaced other Share icons with HDS icons
- Updated the svgs in assets as they are used in askem

### Closes

**[HH-349](https://helsinkisolutionoffice.atlassian.net/browse/HH-349):**
**[TH-1323](https://helsinkisolutionoffice.atlassian.net/browse/TH-1323):**

## Additional notes

[HH-349]: https://helsinkisolutionoffice.atlassian.net/browse/HH-349?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[TH-1323]: https://helsinkisolutionoffice.atlassian.net/browse/TH-1323?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by terovirtanen** [comment]
**Hobbies-Helsinki branch is deployed to platta: https://harrastukset-pr659.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Events-Helsinki branch is deployed to platta: https://tapahtumat-pr659.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Sports-Helsinki branch is deployed to platta: https://liikunta-pr659.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://harrastukset-pr659.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://tapahtumat-pr659.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://liikunta-pr659.dev.hel.ninja :laughing::tada::tada::tada:

**Review by nikomakela — APPROVED** [review]
If the icons are no longer needed at all (in the shared assets) since they can be used from the HDS, shouldn't we just remove them?

**Comment by terovirtanen** [comment]
**Events-Helsinki branch is deployed to platta: https://tapahtumat-pr659.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Hobbies-Helsinki branch is deployed to platta: https://harrastukset-pr659.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://tapahtumat-pr659.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://harrastukset-pr659.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**Sports-Helsinki branch is deployed to platta: https://liikunta-pr659.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://liikunta-pr659.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by karisal-anders** [comment]
A draft PR—needs to be tested!—for using HDS icons from hds-core with askem and removing unused icons/svgs/styles:
- https://github.com/City-of-Helsinki/events-helsinki-monorepo/pull/660

**Pull request merged**
