### PR TITLE
fix(proxy): providerContactInfo field type should be a LocalizedObject

### PR DESCRIPTION
**Pull request by nikomakela**
HH-337

### CODE REVIEW

**Review by karisal-anders — APPROVED** [review]
What about these?
- https://github.com/City-of-Helsinki/events-helsinki-monorepo/blob/sports-helsinki-v1.18.0/proxies/events-graphql-proxy/src/types/types.ts#L148
- https://github.com/City-of-Helsinki/events-helsinki-monorepo/blob/sports-helsinki-v1.18.0/proxies/events-graphql-proxy/src/types/types.ts#L987-L991
- https://github.com/City-of-Helsinki/events-helsinki-monorepo/blob/sports-helsinki-v1.18.0/proxies/events-graphql-federation/subgraphs/events/events.graphql#L189
- https://github.com/City-of-Helsinki/events-helsinki-monorepo/blob/sports-helsinki-v1.18.0/packages/components/src/types/generated/graphql.tsx#L2910
- https://github.com/City-of-Helsinki/events-helsinki-monorepo/blob/sports-helsinki-v1.18.0/proxies/events-graphql-federation/supergraph.graphql#L4441

**Comment by terovirtanen** [comment]
**EVENTS GRAPHQL PROXY is deployed to platta: https://events-graphql-proxy-pr617.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Federation Router branch is deployed to platta: https://events-graphql-federation-events-pr617.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Federation Router branch is deployed to platta: https://events-graphql-federation-sports-pr617.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Federation Router branch is deployed to platta: https://events-graphql-federation-hobbies-pr617.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Hobbies-Helsinki branch is deployed to platta: https://harrastukset-pr617.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Events-Helsinki branch is deployed to platta: https://tapahtumat-pr617.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Sports-Helsinki branch is deployed to platta: https://liikunta-pr617.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://liikunta-pr617.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**EVENTS GRAPHQL PROXY is deployed to platta: https://events-graphql-proxy-pr617.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**VENUE GRAPHQL PROXY is deployed to platta: https://venue-graphql-proxy-pr617.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __failed__ for https://harrastukset-pr617.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by terovirtanen** [comment]
## TestCafe result is __failed__ for https://tapahtumat-pr617.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Pull request merged**
